#!/usr/bin/env bash
# Generated by Chock. Best-effort guard against exfiltration through the tool channel:
# a network command that UPLOADS data (POST/PUT/form/file) to a host outside the allowlist.
# This is a tool-time floor, NOT a network sandbox -- it stops the obvious `curl -d @secrets
# https://unknown` reflex; determined-adversary containment needs real sandboxing.
set -eu

# The allowlist is the whole policy: hosts your stack legitimately uploads to. Defaults cover
# package registries and code hosting; add your org's own domains. A host matches if it EQUALS
# an entry or ends with ".<entry>" (so api.github.com matches github.com).
ALLOWED_HOSTS="
github.com githubusercontent.com
pypi.org pythonhosted.org
npmjs.org yarnpkg.com
crates.io rubygems.org
golang.org pkg.go.dev
ghcr.io docker.io hub.docker.com quay.io
dl.google.com storage.googleapis.com
localhost 127.0.0.1
"

raw="${CHOCK_RAW_COMMAND-}"
if [ -z "$raw" ]; then
    raw="$*"
fi
[ -z "$raw" ] && exit 0

# A command whose whole job is to PRINT the pattern (documentation, an echo, a comment) is
# not executing it. Skip when the first word is a printer/comment.
first="$(printf '%s' "$raw" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]].*//')"
case "$first" in
    echo | printf | print | : | \#*) exit 0 ;;
esac

# A human-approved exception says so on the line, visibly.
case "$raw" in
    *"pragma: allowlist egress"*) exit 0 ;;
esac

shopt -s nocasematch 2>/dev/null || true

# A network client capable of sending a body. No client -> nothing to guard.
fetch_re='(^|[[:space:];|&(<])(curl|wget|iwr|invoke-webrequest|invoke-restmethod|irm)([[:space:]]|$)'
[[ "$raw" =~ $fetch_re ]] || {
    shopt -u nocasematch 2>/dev/null || true
    exit 0
}

# Upload intent -- the thing that turns a fetch into an exfiltration. Fetch-only (a bare GET)
# is left alone: the target is upload/POST to an unapproved host, not normal dependency traffic.
#   curl:  -d/--data*/-F/--form/-T/--upload-file, -X|--request POST|PUT|PATCH
#   wget:  --post-data/--post-file/--body-data/--body-file/--method= POST|PUT
#   PS:    -Method POST|PUT|PATCH, -Body, -InFile, -Form
upload_re='(-d[[:space:]]|--data([[:space:]]|-)|[[:space:]]-F[[:space:]]|--form[[:space:]]|[[:space:]]-T[[:space:]]|--upload-file|--post-data|--post-file|--body-data|--body-file|(-X|--request|--method[[:space:]=])[[:space:]=]*(POST|PUT|PATCH)|-Method[[:space:]]+(POST|PUT|PATCH)|-Body[[:space:]]|-InFile[[:space:]]|-Form[[:space:]])'
[[ "$raw" =~ $upload_re ]] || {
    shopt -u nocasematch 2>/dev/null || true
    exit 0
}

_host_allowed() {
    local host="$1" a
    for a in $ALLOWED_HOSTS; do
        [[ "$host" == "$a" || "$host" == *".$a" ]] && return 0
    done
    return 1
}

# Every http(s) URL target in the command. An upload to any host NOT on the allowlist blocks.
# strip credentials (user:pass@) and any :port before matching the host.
bad_host=""
while read -r url; do
    [ -z "$url" ] && continue
    host="${url#*://}"
    host="${host%%/*}"
    host="${host##*@}"
    host="${host%%:*}"
    [ -z "$host" ] && continue
    if ! _host_allowed "$host"; then
        bad_host="$host"
        break
    fi
done < <(printf '%s\n' "$raw" | grep -oiE 'https?://[^[:space:]"'"'"'()<>]+' || true)

shopt -u nocasematch 2>/dev/null || true

if [ -n "$bad_host" ]; then
    echo "BLOCKED: uploading data to '$bad_host' is outside the egress allowlist. Send it only to an approved host, or add the host to ALLOWED_HOSTS, or mark a reviewed exception with 'pragma: allowlist egress' on the line." >&2
    exit 1
fi

exit 0
