#!/usr/bin/env bash
# Generated by Chock. Refuses shell commands that write to agent-config or vendored
# enforcement paths -- the agent must not hand-edit its own authority. Reads pass;
# `chock sync` passes (it writes through the tool, not shell editing). Best-effort
# and coarse by design: when in doubt it blocks, and the fix is a two-step command
# or a human-approved run carrying 'chock: approved-config-change'.
set -eu

# Include the raw command string: Windows path forms and `bash -c "..."` payloads
# arrive here as one argument, and CHOCK_RAW_COMMAND carries the pre-split original.
full="$* ${CHOCK_RAW_COMMAND:-}"
# Normalize backslashes to forward slashes so a Windows `.claude\settings.json` matches
# the same protected patterns as its POSIX form.
norm="${full//\\//}"

# A human-approved change says so in the command itself, visibly.
case "$full" in
    *"chock: approved-config-change"*) exit 0 ;;
esac

# Interpreters invoked in a *writing* form: a code/in-place flag that appears AFTER an
# interpreter token WITHIN THE SAME command string, so option order does not matter
# (python -O -c, perl -0777 -i, node --eval) yet a `bash -c` wrapper's own -c -- which
# precedes any interpreter -- is not misattributed. The argv and the raw command are
# scanned SEPARATELY (never concatenated) so one string's interpreter cannot pair with
# another string's flag. Globbing is disabled during the split so a literal * is not
# expanded against the filesystem. A bare `python script.py path` read has no write flag.
_interp_write() {
    local seen=0 tok
    set -f
    for tok in $1; do
        case "$tok" in
            python|python3|perl|ruby|node) seen=1 ;;
            -c|-e|--eval|-i|--in-place|-i.*|-pi|-pi.*|-ni|-ne)
                if [ "$seen" -eq 1 ]; then set +f; return 0; fi ;;
        esac
    done
    set +f
    return 1
}

has_writer=0
# In-place editors and shell redirection (substring: reaches bash -c payloads).
case "$full" in
    *"sed -i"*|*"--in-place"*|*">"*) has_writer=1 ;;
esac
# Deleters, movers, and raw writers as whole tokens.
for arg in "$@"; do
    case "$arg" in
        tee|rm|mv|cp|chmod|truncate|patch|dd|ed|ex) has_writer=1 ;;
    esac
done
# Interpreter write-forms (argv and raw command scanned independently).
if _interp_write "$*" || _interp_write "${CHOCK_RAW_COMMAND:-}"; then
    has_writer=1
fi
if [[ "$has_writer" -eq 0 ]]; then
    exit 0
fi

# Protected paths, matched against the backslash-normalized command line. Includes the
# policy guard sources themselves (.agents/policies/<id>/implementations/) -- an agent
# must not rewrite the very guard the compiled hook executes.
protected=""
case "$norm" in
    *AGENTS.md*|*CLAUDE.md*|*GEMINI.md*|*copilot-instructions.md*| \
    *.cursorrules*|*.windsurfrules*|*.aider.conf.yml*| \
    *.claude/settings*|*.mcp.json*| \
    *.chock/bin/*|*.chock/compiled/*|*.git/hooks/*| \
    *.agents/policies/*implementations*)
        protected=yes
        ;;
esac

if [[ -n "$protected" ]]; then
    echo "BLOCKED: shell write touching agent config is not allowed -- an agent must not edit its own guardrails. Regenerate managed files with \`chock sync\`, or have a human approve by including 'chock: approved-config-change' in the command." >&2
    exit 1
fi

exit 0
