<project>
  <properties>
    <log4j.version>2.24.1</log4j.version>
  </properties>
  <repositories>
    <repository><id>central</id><url>https://repo.maven.apache.org/maven2</url></repository>
    <repository><id>local</id><url>http://localhost:8081/repository/maven-public/</url></repository>
  </repositories>
  <scm><url>http://github.com/acme/app</url></scm>
  <dependencyManagement>
    <dependencies>
      <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-dependencies</artifactId><version>3.3.4</version><type>pom</type><scope>import</scope></dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency><groupId>org.springframework</groupId><artifactId>spring-webmvc</artifactId></dependency>
    <dependency><groupId>org.apache.logging.log4j</groupId><artifactId>log4j-core</artifactId><version>${log4j.version}</version></dependency>
    <dependency><groupId>org.yaml</groupId><artifactId>snakeyaml</artifactId><version>2.2</version></dependency>
    <dependency><groupId>org.apache.commons</groupId><artifactId>commons-text</artifactId><version>1.12.0</version></dependency>
    <dependency><groupId>com.google.guava</groupId><artifactId>guava</artifactId><version>[33.0-jre,34.0)</version></dependency>
  </dependencies>
</project>
