#!/usr/bin/env bash
# Auto-generated by chock compile. Script-backed gate: protect-commit-privacy
# The guard reads the change itself from git; its exit code is the verdict: 0 allows, 3 asks and
# 4 warns (both settled by the gate runner), anything else refuses. Only commit-msg passes an
# argument (the message file's path).
set -eu
repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"
guard="$repo_root/.agents/policies/protect-commit-privacy/implementations/protect-commit-privacy-commit-msg.py"
if [ ! -f "$guard" ]; then
  echo "gate: protect-commit-privacy ships no guard at .agents/policies/protect-commit-privacy/implementations/protect-commit-privacy-commit-msg.py" >&2
  exit 2
fi
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1 && "$c" -c 'import tomllib' >/dev/null 2>&1; then PY="$c"; break; fi
done
case "$guard" in
  *.py)
    [ -n "$PY" ] || { echo "gate: no python >= 3.11 (with tomllib) found on PATH" >&2; exit 2; }
    rc=0
    "$PY" "$guard" "$@" || rc=$?
    ;;
  *)
    command -v bash >/dev/null 2>&1 || { echo "gate: no bash found on PATH" >&2; exit 2; }
    rc=0
    bash "$guard" "$@" || rc=$?
    ;;
esac
case "$rc" in
  3|4)
    [ -n "$PY" ] || { echo "gate: protect-commit-privacy asked or warned, and no python >= 3.11 (with tomllib) is on PATH to settle it" >&2; exit 1; }
    exec "$PY" "$repo_root/.chock/bin/gate.py" script-verdict --policy protect-commit-privacy --event commit-msg --exit "$rc"
    ;;
  *) exit "$rc" ;;
esac
