"""protect-agent-config: commands of the sixth review round, each refused or allowed."""

from __future__ import annotations

ESCAPE_REFUSED = [
    "echo -e 'echo x > \\0056mcp.json' | sh",
    "printf '%b' 'echo x > \\0056mcp.json' | sh",
    "printf 'echo x > \\056mcp.json\\n' | sh",
    "printf '%b' 'echo x > \\56mcp.json' | sh",
    "echo -e 'echo x > \\x2emcp.json' | sh",
    "echo -e 'echo x > .mcp.json' | sh",
    "echo -e 'echo x > \\U0000002emcp.json' | sh",
    "printf 'echo x > \\x2emcp.json' | sh",
    "printf '%b' 'echo x > .mcp.json' | sh",
    "echo -e 'echo x > \\0056mcp.json\\c' | sh",
    "echo $'echo x > \\056mcp.json' | sh",
    "echo x > $'\\056mcp.json'",
    "echo x > $'\\x2emcp.json'",
    "echo x > $'.mcp.json'",
    "echo x > $'\\U0000002emcp.json'",
    "echo x > $'\\UFFFFFFFF.mcp.json'",
    "echo x > .mcp.json; echo $'\\UFFFFFFFF'",
    "echo x > .mcp.json; echo $'\\ud800'",
]

ESCAPE_ALLOWED = [
    "echo -e 'echo hi\\0056' | sh",
    "printf '%b' 'echo \\0101' | sh",
    "echo $'a\\tb' > notes.txt",
    "printf '%b%s' 'echo hi\\cx' y | sh",
]

MKTEMP_REFUSED = [
    "x=$(mktemp); trap 'x=.mcp.json' DEBUG; echo > $x",
    "x=$(mktemp); trap 'x=.mcp.json' ERR; false; echo > $x",
    "x=$(mktemp); trap 'x=.mcp.json' USR1; kill -USR1 $$; echo > $x",
    "x=$(mktemp); trap 'x=.mcp.json' RETURN; echo > $x",
    "x=$(mktemp); eval \"trap 'x=.mcp.json' DEBUG\"; echo > $x",
    "x=$(mktemp); t='trap \"x=.mcp.json\" DEBUG'; $t; echo > $x",
    'x=$(mktemp); trap "x=.mcp.json" EXIT; echo > $x',
    "x=$(mktemp); n=x; read $n <<< .mcp.json; echo z > $x",
    'x=$(mktemp); n=x; read -r "$n" <<< .mcp.json; echo z > $x',
    "x=$(mktemp); n=x; printf -v $n .mcp.json; echo z > $x",
    'x=$(mktemp); n=x; printf -v "$n" .mcp.json; echo z > $x',
    "x=$(mktemp); n=x; printf -v ${n}[0] .mcp.json; echo z > $x",
    "x=$(mktemp); n=x; mapfile $n <<< .mcp.json; echo z > $x",
    "x=$(mktemp); n=x; declare -n r=$n; r=.mcp.json; echo z > $x",
    "x=$(mktemp); n=x; typeset -n r=$n; r=.mcp.json; echo z > $x",
    "x=$(mktemp); n=x; local -n r=$n; r=.mcp.json; echo z > $x",
    'x=$(mktemp); n=x; export "$n=.mcp.json"; echo z > $x',
    "x=$(mktemp); n=x; declare $n=.mcp.json; echo z > $x",
    'x=$(mktemp); n=x; let "$n=1"; echo z > $x',
    "x=$(mktemp); n=x; (( $n = 1 )); echo z > $x",
    "x=$(mktemp); n=x; for $n in .mcp.json; do :; done; echo z > $x",
    "x=$(mktemp); n=x; read -ra $n <<< .mcp.json; echo z > $x",
    "x=$(mktemp); n=x; getopts ab $n; echo z > $x",
    "x=$(mktemp); n=x; $(echo read) $n <<< .mcp.json; echo z > $x",
    "x=$(mktemp); n=x; ${r:-read} $n <<< .mcp.json; echo z > $x",
]

MKTEMP_ALLOWED = [
    "x=$(mktemp); echo > $x",
    "x=$(mktemp); echo hi > $x; cat $x",
    "x=$(mktemp -d); cp a $x/",
    "x=$(mktemp); read y; echo z > $x",
    'x=$(mktemp); read -p "name $USER: " y; echo z > $x',
    "x=$(mktemp); printf -v y '%s' a; echo z > $x",
    "x=$(mktemp); local y=1; echo z > $x",
]

GITALIAS_REFUSED = [
    "git config alias.x 'rebase -xsh'",
    "git config alias.x 'rebase --ex sh'",
    "git config alias.x 'rebase --exe=sh'",
    "git config alias.x 'rebase -ix sh'",
    "git config alias.x 'rebase -i -xsh'",
    "git config alias.x \"rebase -x'cmd'\"",
    "git config alias.x 'clone --upload-pack=sh . x'",
    "git config alias.x 'clone -u sh . x'",
    "git config alias.x 'fetch --upload-pack=sh'",
    "git config alias.x 'fetch -u sh'",
    "git config alias.x 'pull --upload-pack=sh'",
    "git config alias.x 'ls-remote --upload-pack=sh'",
    "git config alias.x 'push --receive-pack=sh'",
    "git config alias.x 'config core.hooksPath h'",
    "git config alias.x 'config --global core.pager sh'",
    "git config alias.x 'config alias.y !sh'",
    "git config alias.x 'config -e'",
    "git config alias.x 'config -f .git/config a.b c'",
    "git config alias.x 'clone -c core.fsmonitor=sh a b'",
    "git config alias.x 'init --template=t'",
    "git config alias.x '!sh -c \"echo hi\"'",
    "git config alias.x '!echo y > .mcp.json'",
    "git -c alias.x='!echo y > .mcp.json' x",
    "git -c alias.x='!sh' x",
    "git config alias.x 'log --output=.mcp.json'",
    "git config alias.x 'format-patch -o .claude'",
    "git config alias.x 'merge -s sh'",
    "git config alias.x 'merge --strategy=sh b'",
    "git config alias.x 'archive --remote=x --exec=sh'",
    "git lg .mcp.json",
    "git x -- .claude/settings.json",
    "git co -- AGENTS.md",
]

GITALIAS_ALLOWED = [
    "git config alias.co checkout",
    "git config alias.st 'status -s'",
    "git config alias.lg 'log --oneline --graph'",
    "git config alias.amend 'commit --amend --no-edit'",
    "git lg",
    "git st",
    "git diff .mcp.json",
    "git log -- AGENTS.md",
    "git show HEAD:.mcp.json",
    "git status",
    "git lfs pull",
]
