"""protect-agent-config: wrappers, find -exec and inline-code interpreters, each refused or allowed."""

from __future__ import annotations

WRAPPERS_REFUSED = [
    "su -c 'echo x > .mcp.json'",
    "su root -c 'echo x > .mcp.json'",
    "su - user -c 'echo x > .mcp.json'",
    "env -S 'echo x > .mcp.json'",
    "env -S 'sh -c \"echo x > .mcp.json\"'",
    "fakeroot rm .mcp.json",
    "fakeroot -- rm .mcp.json",
    "unshare -r rm .mcp.json",
    "unshare -m --fork rm .mcp.json",
    "unshare --map-root-user rm .mcp.json",
    "flock /srv/l rm .mcp.json",
    "flock -c 'echo x > .mcp.json' /srv/l",
    "flock /srv/l -c 'echo x > .mcp.json'",
    "flock -n /srv/l rm .mcp.json",
    "taskset 0x1 rm .mcp.json",
    "taskset -c 0 rm .mcp.json",
    "chrt 10 rm .mcp.json",
    "chrt -f 10 rm .mcp.json",
    "strace rm .mcp.json",
    "strace -o /srv/out rm .mcp.json",
    "strace -f -o /srv/o rm .mcp.json",
    "ltrace rm .mcp.json",
    "watch rm .mcp.json",
    "watch -n 1 rm .mcp.json",
    "unbuffer rm .mcp.json",
    "busybox rm .mcp.json",
    "busybox sh -c 'rm .mcp.json'",
    "fish -c 'echo x > .mcp.json'",
    "csh -c 'echo x > .mcp.json'",
    "tcsh -c 'echo x > .mcp.json'",
    "ksh -c 'echo x > .mcp.json'",
    "dash -c 'echo x > .mcp.json'",
    "zsh -c 'echo x > .mcp.json'",
    "coproc echo x > .mcp.json",
    "coproc rm .mcp.json",
    "coproc NAME { rm .mcp.json; }",
    "trap 'rm .mcp.json' EXIT",
    "trap 'rm .mcp.json' INT TERM EXIT",
    "trap 'echo x > .mcp.json' EXIT",
    "su -c 'rm .claude/settings.json'",
    "unshare --weird-opt val rm .mcp.json",
    "flock --weird 1 /srv/l rm .mcp.json",
    "taskset --weird 1 0x1 rm .mcp.json",
    "strace -X foo rm .mcp.json",
    "chrt --weird 1 10 rm .mcp.json",
    "su -s /bin/sh -c 'rm .mcp.json'",
    "nsenter -t 1 rm .mcp.json",
    "setpriv --reuid 0 rm .mcp.json",
    "chroot /x rm .mcp.json",
    "stdbuf -oL rm .mcp.json",
]

WRAPPERS_ALLOWED = [
    "su -c 'ls'",
    "su -c 'echo hi > out.txt'",
    "env -S 'echo hi'",
    "fakeroot make",
    "unshare -r make",
    "flock /srv/l make",
    "flock -c 'make' /srv/l",
    "taskset 0x1 make",
    "chrt 10 make",
    "strace -o /srv/o ls",
    "ltrace ls",
    "watch ls",
    "unbuffer make",
    "busybox ls",
    "fish -c 'ls'",
    "ksh -c 'ls'",
    "dash -c 'ls'",
    "zsh -c 'ls'",
    "coproc ls",
    "trap 'echo bye' EXIT",
    "trap 'rm -f /srv/x' EXIT INT",
    "trap - EXIT",
    "trap",
    "flock /srv/l cat .mcp.json",
    "strace -o /srv/o cat .mcp.json",
    "watch cat .mcp.json",
]

FIND_REFUSED = [
    "find . -name '*.md' -delete",
    "find . -type f -exec rm {} +",
    "find . -exec sh -c 'rm {}' \\;",
    "find . -exec foo {} \\;",
    "find . -exec python3 x.py {} \\;",
    "find . -exec sed -i s/a/b/ {} +",
    "find . -exec chmod 600 {} +",
    "find . -fprint .mcp.json",
    "find . -exec tee {} \\;",
    "find . -exec mv {} /srv \\;",
    "find . -delete",
    "find . -exec cp a {} \\;",
    "find . -exec bash -c 'echo x > $0' {} \\;",
    "find . -exec $X {} \\;",
    "find . -name '*.json' -exec truncate -s 0 {} +",
    "find . -exec grep -l x {} + -exec rm {} +",
]

FIND_ALLOWED = [
    "find . -type f -exec grep -l x {} +",
    "find . -type f -exec cat {} \\;",
    "find . -exec echo {} \\;",
    "find . -exec ls {} \\;",
    "find . -exec file {} \\;",
    "find . -exec stat {} \\;",
    "find . -exec md5sum {} +",
    "find . -execdir head {} \\;",
    "find . -ok wc -l {} \\;",
    "find . -exec sha256sum {} +",
    "find . -exec printf '%s' {} \\;",
    "find . -exec test -f {} \\;",
    "find . -exec diff {} /dev/null \\;",
    "find . -name '*.py' -exec tail {} \\;",
    "find . -type f | head",
    "find . -name '*.py' -print",
    "find .claude -type f -exec cat {} +",
    "find . -exec grep x {} \\; -print",
]

CODE_REFUSED = [
    'php -r \'file_put_contents(".mcp.json", "x");\'',
    'lua -e \'io.open(".mcp.json","w")\'',
    'deno eval \'Deno.writeTextFileSync(".mcp.json", "x")\'',
    'bun -e \'Bun.write(".mcp.json", "x")\'',
    "awk 'BEGIN{system(\"rm .mcp.json\")}'",
    'awk \'BEGIN { print "x" > ".mcp.json" }\'',
    'awk \'BEGIN { print "x" >> ".mcp.json" }\'',
    "sed -n '1e rm .mcp.json' a",
    "sed 'e rm .mcp.json' a",
    "sed -n 'w .mcp.json' a",
    "sed 'w .claude/settings.json' a",
    "sed -n '/x/w .mcp.json' a",
    "sed 's/a/b/w .mcp.json' a",
]

CODE_ALLOWED = [
    "awk '{system(\"touch x\")}' a",
    "gawk 'BEGIN{system(\"ls\")}'",
    "sed -e '1e id' a",
    "sed 's/a/b/e' a",
    "php -r 'echo 1;'",
    "lua -e 'print(1)'",
    "deno eval 'console.log(1)'",
    "bun -e 'console.log(1)'",
    "awk '{print $1}' a",
    'awk \'BEGIN { print "x" > "out.txt" }\'',
    "sed -n 'w out.txt' a",
    "sed 's/a/b/' a",
    "sed -n '1p' a",
    "awk '{print > \"b.txt\"}' a",
]
