"""Command lines and verdicts for the git, destructive-action and agent-spawn guards."""

BLOCK, ASK, OK = 1, 3, 0

CASES: dict[str, list[tuple[str, int]]] = {
    "block-no-verify": [
        ("cd repo && git commit --no-verify", BLOCK),
        ("cd repo; git commit -m x --no-verify", BLOCK),
        ("bash -c 'git commit --no-verify'", BLOCK),
        ("sudo -u root bash -lc 'git push --no-verify'", BLOCK),
        ("env FOO=1 git commit --no-verify", BLOCK),
        ("git ls-files | xargs git commit --no-verify", BLOCK),
        ("git commit --no-veri", BLOCK),
        ("git commit -n", BLOCK),
        ("git commit -an", BLOCK),
        ("git push --no-verify origin main", BLOCK),
        ("git -C repo commit --no-verify", BLOCK),
        ("git config core.hooksPath /dev/null", BLOCK),
        ("git config --global core.hookspath /dev/null", BLOCK),
        ("git -c core.hooksPath=/dev/null commit", BLOCK),
        ("git -c core.hooksPath=/dev/null push", BLOCK),
        ("git --config-env=core.hooksPath=EVIL commit", BLOCK),
        ("GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0=/dev/null git commit -m x", BLOCK),
        ("export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.hooksPath GIT_CONFIG_VALUE_0=/x\ngit push", BLOCK),
        ("GIT_CONFIG_PARAMETERS=\"'core.hookspath=/dev/null'\" git commit", BLOCK),
        ("git commit -m ';' --no-verify", BLOCK),
        ("git commit -m 'a' -- --no-verify", OK),
        ("git commit -m 'hello'", OK),
        ('git commit -m "-n stays in the message"', OK),
        ("git commit -F msg.txt", OK),
        ("git commit -mnote", OK),
        ("git commit --no-verbose", OK),
        ("git commit --no-ver", OK),
        ("echo git commit --no-verify", OK),
        ("git push -n", OK),
        ("git push --dry-run", OK),
        ("git status -- commit -c core.hooksPath=/tmp", OK),
        ("git config --get core.hooksPath", OK),
        ("git config core.hooksPath", OK),
        ("git config --unset core.hooksPath", OK),
        ("git config user.name x", OK),
        ("git -c user.name=x commit -m y", OK),
        ("GIT_CONFIG_COUNT=abc git commit -m y", OK),
        ("GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=user.name git commit -m y", OK),
        ("git --version", OK),
        ("ls -la", OK),
    ],
    "block-destructive-commands": [
        ("bash -c 'rm -rf /'", BLOCK),
        ("cd x && rm -rf /", BLOCK),
        ("sudo bash -c 'rm -rf ~/work'", BLOCK),
        ("echo /srv/a /abs | xargs rm -rf /abs", BLOCK),
        ("rm -rf $HOME/x", BLOCK),
        ("rm -Rf ..", BLOCK),
        ("rm --recursive --force /", BLOCK),
        ("rm -rf build", OK),
        ("rm -r /srv/x", OK),
        ("echo rm -rf /", OK),
        ("git commit -m 'rm -rf /'", OK),
        ("git push --force", BLOCK),
        ("env A=1 git push -f origin main", BLOCK),
        ("git push -fu origin main", BLOCK),
        ("git push origin +main", BLOCK),
        ("git push origin HEAD:+main", BLOCK),
        ("git push --force-with-lease", OK),
        ("git push origin main", OK),
        ("git reset --hard", BLOCK),
        ("git reset --har HEAD~1", BLOCK),
        ("git reset --soft HEAD~1", OK),
        ("git clean -fd", BLOCK),
        ("git clean --force", BLOCK),
        ("git clean -n", OK),
        ("git checkout .", BLOCK),
        ("git checkout main", OK),
        ("git status", OK),
        ("git branch -D topic", ASK),
        ("git branch -df topic", ASK),
        ("git branch --delete --force topic", ASK),
        ("git branch -d topic", OK),
        ("git branch", OK),
        ("git branch -D topic && git reset --hard", BLOCK),
        ("git branch -D a && git branch -D b", ASK),
        ("kubectl delete pod x", BLOCK),
        ("kubectl -n prod delete pod x", BLOCK),
        ("kubectl get pods delete", OK),
        ("terraform destroy", BLOCK),
        ("terraform plan destroy-me", OK),
        ("aws s3 rm s3://b --recursive", BLOCK),
        ("aws --profile p s3 rb s3://b --force", BLOCK),
        ("aws s3 ls delete", OK),
        ("aws s3 rm s3://b/key", OK),
        ("dropdb prod", BLOCK),
        ("helm uninstall web", BLOCK),
        ("helm --kube-context prod delete web", BLOCK),
        ("helm del web", BLOCK),
        ("helm un web", BLOCK),
        ("helm list delete", OK),
        ("helm", OK),
        ("docker volume rm v", BLOCK),
        ("docker volume remove v", BLOCK),
        ("docker volume prune", BLOCK),
        ("docker system prune -af", BLOCK),
        ("docker ps volume", OK),
        ("gcloud compute instances delete x", BLOCK),
        ("gcloud compute instances list", OK),
        ("find / -delete", BLOCK),
        ("find . -name '*.o' -delete", BLOCK),
        ("find /var -exec rm {} ;", BLOCK),
        ("find . /etc -exec rm {} ;", BLOCK),
        ("find -delete", BLOCK),
        ("find . -name x", OK),
        ("shred -u /etc/passwd", BLOCK),
        ("shred local.txt", OK),
        ("truncate -s0 /etc/x", BLOCK),
        ("wipefs -a /dev/sda", BLOCK),
        ("wipefs /dev/sda", OK),
        ("Remove-Item -Recurse -Force C:\\", BLOCK),
        ("rd /s C:\\", BLOCK),
        ("Remove-Item -Recurse build", OK),
    ],
    "rtk-dangerous-actions-blocker": [
        ("rm -rf /", BLOCK),
        ("bash -c 'rm -rf ~'", BLOCK),
        ("rm -rf src", ASK),
        ("rm -rf node_modules dist", OK),
        ("rm -rf build/", OK),
        ("rm -r src", OK),
        ("git push -f", BLOCK),
        ("git push origin +main", BLOCK),
        ("git push", OK),
        ("git reset --hard", ASK),
        ("git clean -f", ASK),
        ("git checkout .", ASK),
        ("git branch -D x", ASK),
        ("git branch -d x", OK),
        ("git status", OK),
        ("cat .env", BLOCK),
        ("grep KEY .env", BLOCK),
        ("grep KEY < .env", BLOCK),
        ("cd app && cat .env.production", BLOCK),
        ("sed -n 1p ~/.ssh/id_rsa", BLOCK),
        ("cat --file=.env", BLOCK),
        ("awk 1 credentials", BLOCK),
        ("cat id_ed25519.pub.key", BLOCK),
        ("cat .env.example", OK),
        ("cat README.md", OK),
        ("echo $API_KEY", BLOCK),
        ("echo ${DB_PASSWORD}", BLOCK),
        ("printf '%s' $GITHUB_TOKEN", BLOCK),
        ("echo $HOME", OK),
        ("echo done", OK),
        ("API_KEY=abc123 ./run.sh", BLOCK),
        ("API_KEY=$KEY ./run.sh", OK),
        ("API_KEY= ./run.sh", OK),
        ("psql -c 'DROP TABLE users'", BLOCK),
        ("psql -c 'TRUNCATE users'", BLOCK),
        ("psql -c 'DELETE FROM users;'", BLOCK),
        ("psql -c 'DELETE FROM users WHERE id=1'", OK),
        ("redis-cli FLUSHALL", BLOCK),
        ("mysql <<SQL\ndrop database x;\nSQL", BLOCK),
        ("psql -c 'select 1'", OK),
        ("dropdb prod", BLOCK),
        ("kubectl delete ns x", BLOCK),
        ("terraform destroy", BLOCK),
        ("aws s3 rm s3://b --recursive", BLOCK),
        ("aws s3 rb s3://b --force", BLOCK),
        ("aws s3 ls", OK),
        ("helm uninstall x", BLOCK),
        ("helm list", OK),
        ("gcloud projects delete p", BLOCK),
        ("gcloud projects list", OK),
        ("docker system prune", ASK),
        ("docker volume prune", ASK),
        ("docker image prune", ASK),
        ("docker network prune", ASK),
        ("docker volume rm v", BLOCK),
        ("docker rm -f $(docker ps -aq)", ASK),
        ("docker rm -f `docker ps -aq`", ASK),
        ("docker rm -f web", OK),
        ("docker ps", OK),
        ("docker exec web cat .env", OK),
        ("docker exec -it -e A=1 web psql -c 'DROP TABLE x'", BLOCK),
        ("docker exec web rm -rf /", OK),
        ("kubectl exec pod -- psql -c 'drop table x'", BLOCK),
        ("kubectl exec pod -- ls", OK),
        ("kubectl -n prod exec pod -- ls", OK),
        ("docker exec", OK),
        ("Remove-Item -Recurse -Force C:\\", BLOCK),
        ("Remove-Item -Recurse build", OK),
    ],
}
