"""protect-agent-config: commands that reach a protected path only once cd, `..`, variables, globs or a directory are resolved."""

REFUSED = [
    "cd .cursor && echo x > mcp.json",
    "cd .claude; tee settings.json",
    "pushd .chock; echo x > config.yaml",
    "cd .cursor && sed -i s/a/b/ mcp.json",
    "cd src && cd ../.cursor && echo x > mcp.json",
    "cd .. && echo x > AGENTS.md",
    "D=.cursor; echo x > $D/mcp.json",
    'D=.claude; echo x > "${D}/settings.json"',
    "echo x > $(echo .cursor/mcp.json)",
    "echo x > `echo .claude/settings.json`",
    "echo x > .cursor/x/../mcp.json",
    "echo x > x/../.mcp.json",
    "echo x > src/../.chock/config.yaml",
    "echo x > .cursor/mcp.jso[n]",
    "echo x > .cursor/mcp.*",
    "tee .claude/sett*",
    "echo x > AGENT?.md",
    "mv .cursor /tmp/old",
    "ln -s /tmp/x .cursor",
    "rm -r .cursor",
    "rm -r .claude",
    "rm -r .chock",
    "cp -r evil/ .cursor",
    "cp -r evil/* .cursor/",
    "cp evil/mcp.json .cursor/",
    "cp -t .cursor evil/mcp.json",
    "cd $DIR && echo x > mcp.json",
    "cd - && echo x > mcp.json",
    "X='echo y > .cursor/mcp.json'; eval \"$X\"",
    'bash -c "$CMD" > .mcp.json',
    "echo x | tee $OUT",
    "python3 -c \"open('.cursor/x/../mcp.json','w')\"",
    "cd .cursor && python3 -c \"open('mcp.json','w')\"",
    "find .cursor -delete",
    "git rm -r .cursor",
    "rm .cursor/*",
    "rm -rf .cur*",
]
ALLOWED = [
    "cd src && make",
    "cd src; ls -la",
    "pushd src && popd",
    "echo $HOME",
    'echo "$HOME/.config" > notes.txt',
    "cp a b",
    "cp -r src build",
    "ls .cursor",
    "ls -la .claude",
    "cat .mcp.json",
    "cat .chock/config.yaml | head",
    "git diff",
    "git status --short",
    "git log --oneline -5",
    "git add -A",
    "git commit -m 'docs: mention .cursor/mcp.json and rm -r .cursor'",
    "git checkout -b feature/x",
    "git checkout $BRANCH",
    "git restore --staged .",
    "git rm --cached build.log",
    "echo x > .vscode/launch.json",
    "echo x > .github/workflows/ci.yml",
    "python -m chock sync --repo .",
    "python -m pytest tests -q",
    "make test && make lint",
    "npm install && npm test",
    "ruff check . && ruff format --check .",
    "cat $X",
    "grep -rn TODO src/*.py",
    "mkdir -p build/out && cp dist/*.whl build/out/",
    "rm -rf build/* dist/*",
    "rm -rf $TMPDIR/build",
    "rm *.pyc",
    "mv *.log logs/",
    "chmod +x scripts/*.sh",
    "find . -name '*.pyc' -delete",
    "find src -type f -name '*.orig' -exec rm {} +",
    "sed -i '$d' notes.txt",
    "sed -i -e 's/a/b/' src/app.py",
    'eval "$(ssh-agent -s)"',
    'echo "$(date)" > log.txt',
    "cd /tmp && echo x > mcp.json",
    "cd - && ls",
    "cp .mcp.json /tmp/backup",
    "cp -r .cursor /tmp/backup",
    "cat > notes.md <<'EOF'\na note on `rm .mcp.json`\nEOF",
    "python3 -c \"print(open('README.md').read())\"",
    "curl -s https://example.com -o out.html",
    "docker compose up -d",
]
