"""protect-agent-config: ordinary development commands the guard must leave alone (a reviewer's corpus),
and the few of them it asks a person about because a path in a write position is not known."""

ORDINARY = [
    "make build",
    "make test",
    "npm test",
    "npm run build",
    "npm i",
    "npm install",
    "npm ci",
    "pnpm install",
    "yarn install",
    "pip install -e .",
    "pip install -r requirements.txt",
    "pip install .",
    "uv sync",
    "uv pip install -e .",
    "pytest > log",
    "pytest -q > /var/tmp/x",
    "pytest tests/ 2>&1 | tee test.log",
    "python -m pytest tests -x",
    "git status",
    "git diff",
    "git log --oneline -5",
    "git add -A",
    "git add .",
    'git commit -m "fix .mcp.json docs"',
    "git commit -m 'update AGENTS.md and .cursor/mcp.json notes'",
    "git commit -am 'x'",
    "git push origin HEAD",
    "git pull --rebase",
    "git checkout -b feature/x",
    "git checkout main",
    "git switch -c x",
    "git stash",
    "git restore --staged .",
    "git restore src/a.py",
    "git checkout -- src/a.py",
    "git diff HEAD -- AGENTS.md",
    "git show HEAD:AGENTS.md",
    "git log -p -- .mcp.json",
    "cd .cursor && ls",
    "cd .cursor; cat mcp.json",
    "cat .cursor/mcp.json | jq .",
    "jq . .mcp.json",
    "diff AGENTS.md CLAUDE.md",
    "diff -u .cursor/mcp.json /var/tmp/x",
    "grep -r mcp .",
    "grep -rn 'AGENTS.md' docs/",
    "rg mcp .cursor",
    "echo hi > /var/tmp/x",
    "echo hi > build.log",
    "> build.log",
    "echo x | tee out.txt",
    "tee out.txt < /dev/null",
    "ls -la .cursor",
    "ls .claude",
    "cat AGENTS.md",
    "head -5 CLAUDE.md",
    "docker run -v $PWD:/app -w /app node:20 npm test",
    'docker run --rm -v "$(pwd)":/src x make',
    "docker build -t x .",
    "docker compose up -d",
    "cp -r .cursor /var/tmp/backup",
    "cp .mcp.json /var/tmp/",
    "rsync -a .cursor/ /var/tmp/x/",
    "tar czf /var/tmp/x.tgz .cursor",
    "mkdir -p build && cd build && cmake ..",
    "cd src && make",
    "cd ..",
    "cd /var/tmp && ls",
    "cd - ",
    "cd $HOME",
    "cd ~ && ls",
    "rm -rf build dist",
    "rm -rf node_modules",
    "rm -rf $TMPDIR/build",
    "rm -rf ./build",
    "rm -rf .pytest_cache",
    "rm -rf .venv",
    "rm -rf __pycache__",
    "rm -rf .cache",
    "rm -f *.pyc",
    "find . -name '*.pyc' -delete",
    "find . -name __pycache__ -exec rm -rf {} +",
    "find . -type f -name '*.log' -delete",
    "sed -i 's/a/b/' src/a.py",
    "sed -i '' 's/a/b/' src/a.py",
    "sed -n 1,5p AGENTS.md",
    "awk '{print}' AGENTS.md",
    "wc -l AGENTS.md",
    "echo $HOME",
    "export FOO=bar",
    "FOO=bar make",
    "source .venv/bin/activate",
    ". .venv/bin/activate",
    "chmod +x scripts/run.sh",
    "chmod 755 build/x",
    "touch src/new.py",
    "mv old.py new.py",
    "cp a b",
    "ln -s a b",
    "install -m 755 x /usr/local/bin/x",
    "curl -o /var/tmp/x http://x",
    "wget -O /var/tmp/x http://x",
    "echo '#' > notes.txt",
    "echo a; echo b",
    "echo 'a;b' > /var/tmp/c",
    "if true; then echo ok; fi",
    "for i in 1 2 3; do echo $i; done",
    "bash -c 'echo hi'",
    "bash scripts/x.sh",
    "sh -c 'make test'",
    "eval $(ssh-agent -s)",
    "python3 -c 'print(1)'",
    "python script.py",
    "python -m http.server",
    "node -e 'console.log(1)'",
    "perl -e 'print 1'",
    "ruby -e 'puts 1'",
    "npx prettier --check .",
    "ruff check .",
    "black --check .",
    "cat <<EOF > /var/tmp/x\nmention .mcp.json and AGENTS.md\nEOF",
    "cat > notes.md <<'EOF'\nsee .cursor/mcp.json\nEOF",
    'echo "remember to edit .mcp.json" > /var/tmp/note',
    "echo 'AGENTS.md' >> /var/tmp/list",
    "printf '%s\\n' .mcp.json > /var/tmp/x",
    "grep -n 'x' .cursor/mcp.json > /var/tmp/out",
    "chock sync",
    "chock sync --check",
    ".chock/bin/chock sync",
    "ls .chock",
    "cat .chock/config.yaml",
    "cat .chock/security.json | jq .",
    "git diff --stat > /var/tmp/d",
    "git log > /var/tmp/l",
    "gh pr create --title 'fix .mcp.json' --body 'x'",
    "gh pr view 1 --json body > /var/tmp/b",
    "echo x > .vscode/launch.json",
    "echo x > .github/workflows/ci.yml",
    "echo x > .vscode/settings.json",
    "cp x .github/workflows/",
    "rm .github/workflows/x.yml",
    "mkdir .cursor",
    "mkdir -p .cursor/rules",
    "echo x > .gitignore",
    "echo x > README.md",
    "cd .github/workflows && vim ci.yml",
    "cd docs && echo x > a.md",
    "cd $DIR && make",
    "cd $DIR; echo x > out.txt",
    'cd "$dir" && tee out.txt',
    "cd - && echo x > out.txt",
    "echo x > ${TMPDIR}/x",
    'echo x > "$TMPDIR/x"',
    "cp a $HOME/backup",
    "rm -rf $HOME/.cache/x",
    "export OUT=/var/tmp/x; echo x > $OUT",
    "OUT=build/x; echo x > $OUT",
    "docker run -v $PWD/.cursor:/c x",
    "git clone https://x/y.git /var/tmp/y",
    "git clone x ../y",
    'echo "unterminated',
    "echo x > $TMPDIR/out.log",
    'echo x > "$TMPDIR/out.log"',
    "echo x > ${TMPDIR}/out.log",
    "tee $TMPDIR/out.log",
    "cp a $TMPDIR/b.txt",
    "echo x > $BUILD_DIR/out.txt",
    "echo x > $HOME/.cache/y",
    "echo x > $OUT/report.json",
    "cd $DIR && make > build.log",
    "cd $DIR && echo x > out.txt",
    "cd src && echo x > settings.json",
    "git checkout $BRANCH",
    "git restore .",
    "git checkout .",
    "git checkout -- .",
]

ASKED = [
    "cp AGENTS.md /var/tmp/AGENTS.md.bak",
    "echo x > $OUT",
    "tee $F",
    "rm $X",
    "cp a $DEST",
    "echo x > $LOG",
    "echo 'unterminated > x",
    "echo x > $OUT/settings.json",
    "echo x > $OUT/config.toml",
    "echo x > $OUT/mcp.json",
    "echo x > $OUT/hooks.json",
    "echo x > $OUT/config.yaml",
    "echo x > $OUT/bin",
    "echo x > $OUT/state",
    "echo x > $OUT/hooks",
    "cd $DIR && echo x > config.yaml",
    "cd $DIR && echo x > settings.json",
    "cd $DIR && tee mcp.json",
    "cd $DIR && rm -rf bin",
    "cd src/.claude && echo x > settings.json",
    "cd packages/a && echo x > AGENTS.md",
    "echo x > packages/a/.cursor/mcp.json",
    "echo x > sub/.mcp.json",
    "git checkout -- $FILE",
    "git restore $FILE",
]
