"""block-no-verify: an agent hiding the agent markers (CLAUDECODE, AI_AGENT, CHOCK_AGENT_COMMIT) from the gates."""

BLOCK, OK = 1, 0

ROWS: list[tuple[str, int]] = [
    ("unset CLAUDECODE", BLOCK),
    ("unset -v CLAUDECODE", BLOCK),
    ("unset AI_AGENT CHOCK_AGENT_COMMIT", BLOCK),
    ("unset CHOCK_AGENT_COMMIT", BLOCK),
    ("unset -v FOO CLAUDECODE && git commit -m x", BLOCK),
    ("env -u CLAUDECODE git commit -m x", BLOCK),
    ("env -uCLAUDECODE git commit", BLOCK),
    ("env -u FOO -u CLAUDECODE git commit", BLOCK),
    ("env --unset=AI_AGENT git commit -m x", BLOCK),
    ("env --unset AI_AGENT git commit -m x", BLOCK),
    ("sudo env -u CLAUDECODE git push", BLOCK),
    ("env -i git commit -m x", BLOCK),
    ("env -i PATH=/usr/bin git commit -m x", BLOCK),
    ("env --ignore-environment git push", BLOCK),
    ("env - git commit -m x", BLOCK),
    ("env -u FOO -i git commit -m x", BLOCK),
    ("env -i bash -c 'git commit -m x'", BLOCK),
    ("CLAUDECODE= git commit -m x", BLOCK),
    ("CLAUDECODE=0 git commit -m x", BLOCK),
    ("AI_AGENT= git commit", BLOCK),
    ("export CLAUDECODE=", BLOCK),
    ("export AI_AGENT=0 && git commit", BLOCK),
    ("export CLAUDECODE+=x", BLOCK),
    ("declare -x CLAUDECODE=", BLOCK),
    ("export -n CLAUDECODE", BLOCK),
    ("export -n FOO CLAUDECODE", BLOCK),
    ("set -e CLAUDECODE", BLOCK),
    ("Remove-Item Env:CLAUDECODE", BLOCK),
    ("Remove-Item Env:\\AI_AGENT", BLOCK),
    ("ri Env:CHOCK_AGENT_COMMIT", BLOCK),
    ("$env:CLAUDECODE = $null", BLOCK),
    ("$env:CLAUDECODE = ''", BLOCK),
    ("$env:AI_AGENT=''; git commit", BLOCK),
    ("[Environment]::SetEnvironmentVariable('CLAUDECODE',$null)", BLOCK),
    ("bash -c 'unset CLAUDECODE; git commit -m x'", BLOCK),
    ("sh -c 'env -u CLAUDECODE git commit'", BLOCK),
    ('pwsh -Command "Remove-Item Env:CLAUDECODE; git commit"', BLOCK),
    ('pwsh -Command "$env:CLAUDECODE = $null; git commit"', BLOCK),
    ("eval 'export CHOCK_ALLOW=x'; git commit", BLOCK),
    ("eval 'unset CLAUDECODE'; git commit", BLOCK),
    ("bash -c \"eval 'export CHOCK_ALLOW=x'; git commit\"", BLOCK),
    ("echo $CLAUDECODE", OK),
    ("printenv AI_AGENT", OK),
    ("env | grep CLAUDECODE", OK),
    ("grep CLAUDECODE file", OK),
    ("grep -u AI_AGENT file", OK),
    ("echo $env:CLAUDECODE", OK),
    ("Get-Item Env:CLAUDECODE", OK),
    ("env -i FOO=1 python x.py", OK),
    ("env -i git status", OK),
    ("env -u HOME python x.py", OK),
    ("env FOO=1 git commit -m x", OK),
    ("git commit -m 'env -i git commit'", OK),
    ("git commit -m 'unset CLAUDECODE'", OK),
    ('git commit -m "env -u CLAUDECODE"', OK),
    ("unset FOO", OK),
    ("Remove-Item Env:FOO", OK),
    ("Remove-Item build", OK),
    ("export -n FOO", OK),
    ("eval 'echo hi'; git commit -m x", OK),
    ("bash -c 'export CHOCK_TOOL=1'; git status", OK),
]
