"""protect-agent-config: `git config` and git environment routes of the fourth review round, each refused or allowed."""

from __future__ import annotations

CODE_KEYS = [
    "core.hooksPath",
    "core.fsmonitor",
    "core.pager",
    "core.editor",
    "core.sshCommand",
    "core.askPass",
    "core.gitProxy",
    "core.alternateRefsCommand",
    "sequence.editor",
    "diff.external",
    "diff.astextplain.textconv",
    "diff.foo.command",
    "merge.foo.driver",
    "filter.lfs.clean",
    "filter.lfs.smudge",
    "filter.lfs.process",
    "credential.helper",
    "credential.https://example.org.helper",
    "alias.st",
    "alias.co",
    "include.path",
    "includeIf.gitdir:/srv/.path",
    "gpg.program",
    "gpg.ssh.program",
    "uploadpack.packObjectsHook",
    "receive.procReceiveRefs",
    "pager.log",
    "web.browser",
    "browser.foo.cmd",
    "man.foo.cmd",
    "sendemail.smtpServer",
    "remote.origin.uploadpack",
    "remote.origin.vcs",
    "difftool.foo.cmd",
    "mergetool.foo.path",
    "trailer.foo.cmd",
    "submodule.x.update",
]

GIT_CONFIG_REFUSED = [
    *(f"git config {key} x" for key in CODE_KEYS),
    *(f"git config --global {key} x" for key in CODE_KEYS[:4]),
    *(f"git config --local --add {key} x" for key in CODE_KEYS[:4]),
    "git config core.fsmonitor 'touch x'",
    "git config alias.st '!sh -c x'",
    "git config --add core.hooksPath x",
    "git config --replace-all core.pager x",
    "git config --unset core.hooksPath",
    "git config --unset-all core.pager",
    "git config --remove-section core",
    "git config --remove-section alias",
    "git config --rename-section core other",
    "git config --remove-section $S",
    "git config --edit",
    "git config -e",
    "git config --file .git/config user.name x",
    "git config --file=.git/config user.name x",
    "git config -f .git/config user.name x",
    "git config -f.git/config user.name x",
    "git config --file .git/config --add remote.o.url x",
    "git config --file .mcp.json a.b c",
    "git config --file .git/config --unset user.name",
    "git -C .git config core.pager x",
    "git -C .git config --add alias.x '!x'",
    "cd .git; git config core.pager x",
    "cd .git && git config core.editor x",
    "G=$(git rev-parse --git-dir); git config --file $G/config user.name x",
    "git config --file $(git rev-parse --git-path config) user.name x",
    "git config $KEY x",
    "git config CORE.HOOKSPATH x",
    "git -c core.fsmonitor=x status",
    "git -c core.pager=x log",
    "git -ccore.pager=x log",
    "git --config-env=core.pager=PAGER log",
    "GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.fsmonitor GIT_CONFIG_VALUE_0=x git status",
    "GIT_CONFIG_COUNT=2 GIT_CONFIG_KEY_0=user.name GIT_CONFIG_VALUE_0=x GIT_CONFIG_KEY_1=alias.x GIT_CONFIG_VALUE_1=y git x",
    "GIT_CONFIG_KEY_0=core.hooksPath git status",
    "GIT_CONFIG_KEY_0=$K git status",
    "GIT_CONFIG_PARAMETERS=\"'core.pager=x'\" git log",
    "GIT_CONFIG_PARAMETERS=\"'user.name=a' 'alias.x=!y'\" git x",
    "GIT_CONFIG_PARAMETERS='core.editor=x' git commit",
    "export GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.pager; git log",
    "env GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=core.sshCommand git fetch",
    "GIT_CONFIG_KEY_0=core.pager make",
    'GIT_CONFIG_PARAMETERS="\'unterminated" git log',
]

GIT_CONFIG_ALLOWED = [
    "git config user.name x",
    "git config user.email x@example.org",
    "git config --global user.name x",
    "git config --local user.email x@example.org",
    "git config core.autocrlf false",
    "git config pull.rebase true",
    "git config --get core.hooksPath",
    "git config --get-all core.pager",
    "git config --get-regexp 'alias.*'",
    "git config --list",
    "git config -l",
    "git config --list --show-origin",
    "git config --file .git/config --get user.name",
    "git config --file .git/config --list",
    "git config --file .git/config user.name",
    "git config --file .gitmodules submodule.x.url y",
    "git config --file=.gitmodules --get submodule.x.url",
    "git config --type bool --default false core.bare",
    "git config --unset user.signingkey",
    "git config --remove-section user",
    "git config --rename-section user person",
    "git config remote.origin.url https://example.org/r.git",
    "git config --file",
    "git config --unset",
    "git config --remove-section",
    "git config",
    "GIT_CONFIG_COUNT=1 GIT_CONFIG_KEY_0=user.name GIT_CONFIG_VALUE_0=x git status",
    "GIT_CONFIG_PARAMETERS=\"'user.name=x'\" git status",
    "GIT_CONFIG_NOSYSTEM=1 git status",
    "git -c user.name=x commit -m y",
    "git -ccolor.ui=never status",
    "git commit -c HEAD",
]
