"""protect-agent-config v2: writes through a symlink whose target is protected (links laid out by `test_protect_agent_config_links`)."""

from __future__ import annotations

# name -> where the link points, relative to the link (or absolute, with @ROOT@ for the repository folder)
LINKS = {
    "notes.md": "AGENTS.md",
    "cfg": ".claude",
    "cfg2": "./.claude/settings.json",
    "abs": "@ROOT@/.claude/settings.json",
    "chain1": "chain2",
    "chain2": "AGENTS.md",
    "src/up": "../.cursor",
    "deep/a/b": "../../.claude",
    "deeper": ".claude/commands",
    "dangle": ".claude/missing.md",
    "Mixed": ".claude",
    "innocent": "src/real.txt",
    "outside": "@OUT@",
    "loop1": "loop2",
    "loop2": "loop1",
}

REFUSED = [
    "echo x > notes.md",
    "echo x >> notes.md",
    "echo x | tee notes.md",
    "sed -i s/a/b/ notes.md",
    "cp x notes.md",
    "truncate -s 0 notes.md",
    "rm notes.md",
    "echo x > ./notes.md",
    "echo x > src/../notes.md",
    "echo x > cfg/commands/a.md",
    "echo x > cfg/new.md",
    "rm cfg/commands/a.md",
    "cd cfg && echo x > a.md",
    "echo x > cfg2",
    "echo x > abs",
    "echo x > chain1",
    "cd src && echo x > up/rules/a.mdc",
    "echo x > deep/a/b/commands/a.md",
    "echo x > dangle",
    "echo x > Mixed/a.md",
    "echo x > not*.md",
    "echo x > cf*/a.md",
    "echo x > ch?in1",
    "D=cfg; echo x > $D/a.md",
    "bash -c 'echo x > notes.md'",
    "echo x > $PWD/notes.md",
    "rm -rf cfg",
    "mv notes.md moved.md",
    "cp -r x cfg",
    "echo x > cfg\\commands\\a.md",
    "echo x > loop1",
    # `..` after a link leaves the folder the link points into, so the path is read as written, not folded
    "echo x > deeper/../settings.json",
    "echo x > ./deeper/../settings.json",
    "cd deeper && echo x > ../settings.json",
    "echo x > deeper/x/../../settings.json",
    # a link or hard link made from a protected file, which a later write would go through (as `ln` is refused)
    "cp -l AGENTS.md alias",
    "cp -al .claude copy",
    "cp -s $PWD/.claude/settings.json s",
    "cp --link AGENTS.md alias",
    "cp --symbolic-link AGENTS.md alias",
    "cp --sym AGENTS.md alias",
    "cp -rl .claude/commands elsewhere",
    "cp -t out -l AGENTS.md",
]

ALLOWED = [
    "cat notes.md",
    "ls cfg",
    "grep -rn x cfg/commands",
    "echo x > innocent",
    "echo x > src/real.txt",
    "echo x > outside/a.txt",
    "echo x > cfg-not-a-link/a.md",
    "echo x > src/a.md",
    "echo x > no*.txt",
    "mkdir -p out/x",
    "cp -l src/real.txt src/alias.txt",
    "cp -s src/real.txt src/alias.txt",
    "cp AGENTS.md /var/tmp/backup.md",
    "cp -r .claude /var/tmp/claude-copy",
    "cp -t out src/real.txt",
]
