"""Command lines and the table row each must hit (None: allowed), replayed against both policies that read the table.

Every row of chock_destructive's TABLE has a refusing case here, most families an allowed near miss beside it, and
the adversarial forms the parser unwraps (sudo, env, bash -c, xargs, cd chains) for the verbs added in table 1.0.0.
"""

from __future__ import annotations

CASES: list[tuple[str, str | None]] = [
    # rm: force on a dangerous target blocks; -r alone on a root blocks; off the safe list asks
    ("rm -rf /", "rm-rf"),
    ("rm -rf ./", "rm-rf"),
    ("rm -rf .//", "rm-rf"),
    ('rm -rf "$PWD"', "rm-rf"),
    ("rm -rf ${PWD}/", "rm-rf"),
    ("rm -r /", "rm-root"),
    ("rm -r ~", "rm-root"),
    ("rm -R /etc", "rm-root"),
    ("rm --recursive $HOME", "rm-root"),
    ("sudo rm -r /usr/*", "rm-root"),
    ("rm -r //", "rm-root"),
    ("rm -r /srv/app/cache", None),
    ("rm -r src", None),
    ("rm -rf src", "rm-relative"),
    ("rm -rf *", "rm-relative"),
    ("rm -rf $(pwd)", "rm-relative"),
    ("rm -rf node_modules dist", None),
    ("rm -rf dist/*", "rm-relative"),
    ("rm -rf build/", None),
    ("rm -f notes.txt", None),
    # unlink, rmdir, mv, chmod, chown on roots
    ("unlink /", "unlink-root"),
    ("rmdir /home", "unlink-root"),
    ("rmdir build", None),
    ("mv /etc /tmp/etc.bak", "mv-root"),
    ("env LC_ALL=C mv ~ /mnt/old", "mv-root"),
    ("mv -t /tmp /var", "mv-root"),
    ("mv --target-directory=/tmp /usr", "mv-root"),
    ("mv notes.txt /etc", None),
    ("mv /etc/hosts.new /etc/hosts", None),
    ("mv -t /tmp a b", None),
    ("chmod -R 777 /", "chmod-root"),
    ("sudo chmod -R 000 /etc", "chmod-root"),
    ("chmod -R a+rwx ~", "chmod-root"),
    ("chmod -R 755 /", "chmod-root"),
    ("chmod -R 755 ./bin", None),
    ("chmod -R 777 ./public", None),
    ("chmod 777 /", None),
    ("chown -R nobody /", "chown-root"),
    ("chgrp -R staff /usr", "chown-root"),
    ("chown -R me:me ./src", None),
    ("chown me /etc", None),
    # devices
    ("dd if=/dev/zero of=/dev/sda bs=1M", "dd-device"),
    ("sudo dd if=img.iso of=/dev/disk2", "dd-device"),
    ("dd if=/dev/urandom of=/dev/null count=1", None),
    ("dd if=a.img of=b.img", None),
    ("mkfs.ext4 /dev/sdb1", "mkfs"),
    ("mkfs -t xfs /dev/sdb", "mkfs"),
    ("bash -c 'mke2fs /dev/sdc'", "mkfs"),
    ("mkswap /dev/sdd", "mkfs"),
    ("rmdir /s /q C:\\", "powershell-remove"),
    ("find / -name core -delete", "find-delete"),
    ("find / -name core", None),
    ("shred -u /etc/shadow", "shred"),
    ("wipefs -a /dev/sda", "wipefs"),
    # lockout and sabotage
    ("echo key > ~/.ssh/authorized_keys", "authorized-keys"),
    ("cat k.pub >| /root/.ssh/authorized_keys", "authorized-keys"),
    ("tee ~/.ssh/authorized_keys < k.pub", "authorized-keys"),
    ("cp k.pub ~/.ssh/authorized_keys", "authorized-keys"),
    ("rm ~/.ssh/authorized_keys2", "authorized-keys"),
    ("echo key >> ~/.ssh/authorized_keys", None),
    ("tee -a ~/.ssh/authorized_keys < k.pub", None),
    ("wc -l ~/.ssh/authorized_keys", None),
    ("cp ~/.ssh/authorized_keys backup", None),
    ("usermod -L deploy", "account-lock"),
    ("sudo usermod --lock deploy", "account-lock"),
    ("usermod -aG docker deploy", None),
    ("passwd -l root", "account-lock"),
    ("passwd", None),
    ("chattr +i /etc/resolv.conf", "chattr-immutable"),
    ("chattr -R +ia /srv", "chattr-immutable"),
    ("chattr -i notes.txt", None),
    ("kill -9 -1", "kill-all"),
    ("kill -s KILL -1", "kill-all"),
    ("kill -- -1", "kill-all"),
    ("kill -1 4242", None),
    ("kill -9 4242", None),
    ("pkill -f uvicorn", "kill-pattern"),
    ("pkill uvicorn", None),
    ("killall node", "kill-pattern"),
    ("killall -l", None),
    ("crontab -r", "crontab-remove"),
    ("crontab -u ci -r", "crontab-remove"),
    ("crontab -l", None),
    ("systemctl disable sshd", "systemctl-disable"),
    ("sudo systemctl --now mask nginx", "systemctl-disable"),
    ("systemctl status sshd", None),
    # git
    ("git push --delete origin topic", "push-delete"),
    ("git push -d origin topic", "push-delete"),
    ("git push origin :topic", "push-delete"),
    ("git push --prune origin", "push-delete"),
    ("git push --del origin topic", "push-delete"),
    ("bash -c 'git push origin :refs/tags/v1'", "push-delete"),
    ("git push origin :", None),
    ("git push --mirror backup", "push-mirror"),
    ("git push --force-with-lease", "push-lease-bare"),
    ("git push --force-with origin topic", "push-lease-bare"),
    ("git push --force-with-lease=topic origin topic", None),
    ("git push --force-with-lease=topic:abc123 origin topic", None),
    ("git checkout -- .", "checkout-all"),
    ("git checkout HEAD -- ./", "checkout-all"),
    ("git checkout -- :/", "checkout-all"),
    ("git checkout -- src/app.py", None),
    ("git restore .", "restore-all"),
    ("git restore --worktree --staged .", "restore-all"),
    ("git restore --staged .", None),
    ("git restore src/app.py", None),
    ("git stash drop", "stash-drop"),
    ("git stash clear", "stash-drop"),
    ("git stash", None),
    ("git stash pop", None),
    ("git reflog expire --expire=now --all", "history-rewrite"),
    ("git reflog delete HEAD@{1}", "history-rewrite"),
    ("git reflog", None),
    ("git gc --prune=now", "history-rewrite"),
    ("git gc", None),
    ("git filter-branch --tree-filter 'rm x' HEAD", "history-rewrite"),
    ("git filter-repo --path secrets --invert-paths", "history-rewrite"),
    ("git update-ref -d refs/heads/main", "history-rewrite"),
    ("git update-ref refs/heads/x HEAD", None),
    ("git clean -fdx", "clean-force"),
    ("git push -f origin main", "push-force"),
    ("git push origin +main", "push-force-refspec"),
    ("git branch -D topic", "branch-force-delete"),
    ("git reset --hard origin/main", "reset-hard"),
    # infrastructure as code
    ("terraform apply -destroy", "iac-destroy"),
    ("terraform apply --destroy=true -auto-approve", "iac-destroy"),
    ("tofu destroy", "iac-destroy"),
    ("terragrunt run-all destroy", "iac-destroy"),
    ("terragrunt run --all destroy", "iac-destroy"),
    ("pulumi destroy --yes", "iac-destroy"),
    ("pulumi down", "iac-destroy"),
    ("env TF_LOG=1 terraform -chdir=infra destroy", "iac-destroy"),
    ("terraform apply -auto-approve", "iac-auto-approve"),
    ("terraform apply -auto-approve=false", None),
    ("terraform apply -destroy=false", None),
    ("terraform plan -destroy", None),
    ("terraform apply plan.out", None),
    ("pulumi preview", None),
    # cloud and platforms
    ("aws s3api delete-bucket --bucket b", "cloud-delete"),
    ("aws s3api delete-object --bucket b --key k", "cloud-delete"),
    ("aws ec2 terminate-instances --instance-ids i-1", "cloud-delete"),
    ("aws --region us-east-1 cloudformation delete-stack --stack-name s", "cloud-delete"),
    ("aws rds delete-db-instance --db-instance-identifier db", "cloud-delete"),
    ("aws iam delete-role --role-name r", "cloud-delete"),
    ("aws s3 sync ./site s3://b --delete", "cloud-delete"),
    ("aws s3 sync ./site s3://b", None),
    ("aws ec2 describe-instances", None),
    ("aws iam list-roles", None),
    ("aws s3api get-object --bucket b --key k out", None),
    ("az group delete -n rg --yes", "cloud-delete"),
    ("az group list", None),
    ("eksctl delete cluster --name c", "cloud-delete"),
    ("eksctl get cluster", None),
    ("doctl compute droplet delete web", "cloud-delete"),
    ("doctl -t tok compute droplet delete web", "cloud-delete"),
    ("doctl compute droplet list", None),
    ("fly apps destroy my-app", "cloud-delete"),
    ("flyctl destroy my-app -y", "cloud-delete"),
    ("fly -a my-app destroy", "cloud-delete"),
    ("fly deploy", None),
    ("heroku apps:destroy my-app", "cloud-delete"),
    ("heroku pg:reset DATABASE", "cloud-delete"),
    ("heroku logs --tail", None),
    ("vercel remove my-project --yes", "cloud-delete"),
    ("vercel rm my-deployment", "cloud-delete"),
    ("vercel deploy", None),
    ("supabase db reset", "cloud-delete"),
    ("supabase projects delete ref", "cloud-delete"),
    ("supabase db push", None),
    ("gh repo delete o/r --yes", "cloud-delete"),
    ("gh repo view o/r", None),
    ("kubectl drain node-1 --ignore-daemonsets", "kubectl-drain"),
    ("kubectl cordon node-1", None),
    ("kubectl delete pod x", "kubectl-delete"),
    ("helm uninstall web", "helm-uninstall"),
    # containers
    ("docker compose down -v", "compose-down-volumes"),
    ("docker compose -f prod.yml down --volumes", "compose-down-volumes"),
    ("docker-compose down -v", "compose-down-volumes"),
    ("docker compose down", None),
    ("docker compose run -v /src:/src app", None),
    ("docker-compose up -d", None),
    ("docker container prune -f", "docker-prune"),
    ("docker image prune -a", "docker-prune"),
    ("docker system prune -a", "docker-system-prune"),
    ("docker volume prune", "docker-volume"),
    ("docker rm -f $(docker ps -aq)", "docker-rm-substituted"),
    ("docker rm -f web", None),
    # data
    ("dropdb prod", "drop-database"),
    ("mysqladmin -u root drop shop", "drop-database"),
    ("mysqladmin status", None),
    ("psql -c 'DROP TABLE users'", "sql"),
    ("mongosh --eval 'db.dropDatabase()'", "sql"),
    ("mongosh --eval 'db.users.drop()'", "sql"),
    ("redis-cli FLUSHALL", "sql"),
    ("psql -c 'select 1'", None),
    ("docker exec -it db psql -c 'DROP DATABASE shop'", "sql"),
    ("kubectl exec pod -- psql -c 'truncate t'", "sql"),
    ("docker exec -e A=1 -u pg db psql -c 'drop schema s'", "sql"),
    ("docker exec db rm -rf /", None),
    # API deletes with credentials ask
    ('curl -X DELETE -H "Authorization: Bearer $TOKEN" https://api.github.com/repos/o/r', "api-delete"),
    ('curl -XDELETE -H "PRIVATE-TOKEN: $T" https://gitlab.com/api/v4/projects/1', "api-delete"),
    ("curl --request=DELETE -u me:$PW https://api.digitalocean.com/v2/droplets/1", "api-delete"),
    (
        'curl -H "Authorization: Bearer $T" -d \'{"query":"mutation { deleteRepository(id: 1) { id } }"}\' https://api.github.com/graphql',
        "api-delete",
    ),
    ("curl --oauth2-bearer $T -X DELETE --url https://www.googleapis.com/storage/v1/b/x", "api-delete"),
    ("curl -X DELETE -uadmin:$PW https://ec2.amazonaws.com/x", "api-delete"),
    ("curl -X DELETE https://api.github.com/repos/o/r", None),
    ('curl -X DELETE -H "Authorization: Bearer $T" https://example.com/items/1', None),
    ('curl -H "Authorization: Bearer $T" https://api.github.com/user', None),
    ('curl -H "Authorization: Bearer $T" -d \'{"query":"mutation { addStar }"}\' https://api.github.com/graphql', None),
    ("gh api -X DELETE repos/o/r", "api-delete"),
    ("gh api --method=DELETE repos/o/r/git/refs/heads/x", "api-delete"),
    ("gh api graphql -f query='mutation { deleteProjectV2(input: {}) { clientMutationId } }'", "api-delete"),
    ("gh api repos/o/r", None),
    ("gh api graphql -F query='{ viewer { login } }'", None),
    # wrappers the parser unwraps: the verb is judged, not the wrapper
    ("sudo env A=1 bash -c 'usermod -L x'", "account-lock"),
    ("echo /dev/sdb | xargs mkfs.ext4", "mkfs"),
    ("cd infra && terraform destroy", "iac-destroy"),
    ("timeout 60 aws ec2 terminate-instances --instance-ids i-1", "cloud-delete"),
    ("nohup git stash clear", "stash-drop"),
    ("echo terraform destroy", None),
    ("git commit -m 'run terraform destroy and git push --mirror'", None),
]

#: Unbalanced quotes or a trailing backslash: the engine sets CHOCK_ARGV_FALLBACK=1 and the guard reads the raw text.
FALLBACK: list[tuple[str, str | None]] = [
    ("rm -rf / \\", "rm-rf"),
    ("terraform destroy 'unbalanced", "iac-destroy"),
    ('bash -c "usermod -L deploy', "account-lock"),
    ('echo "x; git push --mirror backup', "push-mirror"),
    ("aws ec2 terminate-instances --instance-ids 'i-1", "cloud-delete"),
    ("ls 'unbalanced", None),
    ('echo "it is fine', None),
]
