"""Cases for test_hardening_flags: (path, file text, the finding keys it yields)."""

from __future__ import annotations

PRAGMA = "pragma: allowlist hardening-flag"

CMAKE = [
    ("CMakeLists.txt", "target_compile_options(a PRIVATE -fno-stack-protector)\n", ["no-stack-protector"]),
    ("CMakeLists.txt", 'target_compile_options(a PRIVATE "-O2" "-fno-stack-protector")\n', ["no-stack-protector"]),
    ("sub\\CMakeLists.txt", "add_compile_options(-no-pie)\n", ["no-pie"]),
    ("CMakeLists.txt", "# -fno-stack-protector\nadd_compile_options(-O2) # -no-pie\n", []),
    ("CMakeLists.txt", "#[[ -fno-pie\n-no-pie ]] set(X 1)\n", []),
    ("CMakeLists.txt", "#[==[ -fno-pie ]==] add_compile_options(-no-pie)\n", ["no-pie"]),
    ("CMakeLists.txt", "#[[ never closed -no-pie\n", []),
    ("CMakeLists.txt", "add_compile_options([[ # ]] -no-pie)\n", ["no-pie"]),
    ("CMakeLists.txt", "add_compile_options([=[ -no-pie\n", ["no-pie"]),
    ("CMakeLists.txt", 'set(F "a # b" -no-pie)\n', ["no-pie"]),
    ("CMakeLists.txt", 'set(F "a \\" # b" -no-pie)\n', ["no-pie"]),
    ("CMakeLists.txt", 'set(F "never closed -no-pie\n', ["no-pie"]),
    ("CMakeLists.txt", "target_link_options(a PRIVATE\n  -z\n  execstack\n)\n", ["execstack"]),
    (
        "CMakeLists.txt",
        'message("(")\nset(CMAKE_POSITION_INDEPENDENT_CODE OFF)\n',
        ["cmake-position-independent-code-off"],
    ),
    ("a.cmake", "set(CMAKE_POSITION_INDEPENDENT_CODE ON)\n", []),
    ("a.cmake", 'set(CMAKE_POSITION_INDEPENDENT_CODE "off")\n', ["cmake-position-independent-code-off"]),
    (
        "a.cmake",
        "set_target_properties(t PROPERTIES POSITION_INDEPENDENT_CODE FALSE)\n",
        ["cmake-position-independent-code-off"],
    ),
    (
        "a.cmake",
        "set_property(TARGET t PROPERTY POSITION_INDEPENDENT_CODE 0)\n",
        ["cmake-position-independent-code-off"],
    ),
    ("a.cmake", "set(CMAKE_POSITION_INDEPENDENT_CODE foo-NOTFOUND)\n", ["cmake-position-independent-code-off"]),
    ("a.cmake", "set(MY_POSITION_INDEPENDENT_CODE OFF)\n", []),
    ("a.cmake", "add_compile_definitions(_FORTIFY_SOURCE=0)\n", ["fortify-source-zero"]),
    ("CMakeLists.txt", "(\n" * 70 + "add_compile_options(-no-pie)\n", ["no-pie"]),
]
MAKE = [
    ("Makefile", "CFLAGS = -O2 \\\n  -Wall \\\n  -fno-stack-protector\n", ["no-stack-protector"]),
    ("Makefile", "CFLAGS = -fno-\\\nstack-protector\n", ["no-stack-protector"]),
    ("Makefile", "CFLAGS = -O2\\\n-fno-stack-protector\n", ["no-stack-protector"]),
    ("Makefile", "CFLAGS = -O2 \\\r\n  -fno-stack-protector\r\n", ["no-stack-protector"]),
    ("Makefile", "# note \\\n  -fno-stack-protector\nX = 1\n", []),
    ("Makefile", "X = a \\# -no-pie\n", ["no-pie"]),
    ("Makefile", "X = a # -no-pie\n", []),
    ("Makefile", "# a \\\\\nX = -no-pie\n", ["no-pie"]),
    ("Makefile", "app:\n\t$(CC) -fno-stack-protector -o $@ $<\n", ["no-stack-protector"]),
    ("Makefile", "app:\n\t$(CC) -O2 -o $@ $< # -no-pie\n", []),
    ("Makefile", 'app:\n\techo "# -no-pie"\n', ["no-pie"]),
    ("Makefile", "app:\n\tcc a.c \\\n  -no-pie\n", ["no-pie"]),
    ("Makefile", "app:\n\tcc a.c # \\\n  -no-pie\n", []),
    ("GNUmakefile", "X = -fno-pie\n", ["no-pie-codegen"]),
    ("sub/rules.mk", "X = -fno-PIE\n", ["no-pie-codegen"]),
    ("makefile", "X = -fno-pic -pie -fpie\n", []),
    ("Makefile.am", "X = --no-pie\n", ["no-pie"]),
    ("Makefile.md", "X = -no-pie\n", []),
    ("Makefile", "X = -Wl,-no-pie\n", ["no-pie"]),
    ("Makefile", "X = -U_FORTIFY_SOURCE\n", ["undefine-fortify-source"]),
    ("Makefile", "X = -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2\n", []),
    ("Makefile", "X = -D_FORTIFY_SOURCE=2 -U_FORTIFY_SOURCE\n", ["undefine-fortify-source"]),
    ("Makefile", "X = -D_FORTIFY_SOURCE=0\n", ["fortify-source-zero"]),
    ("Makefile", "X = -D _FORTIFY_SOURCE=0\n", ["fortify-source-zero"]),
    ("Makefile", "X = -Wp,-D_FORTIFY_SOURCE=00\n", ["fortify-source-zero"]),
    ("Makefile", "X = -D_FORTIFY_SOURCE=2 -D_FORTIFY_SOURCE=3\n", []),
    ("Makefile", "X = -Wl,-z,execstack\n", ["execstack"]),
    ("Makefile", "X = -z execstack\n", ["execstack"]),
    ("Makefile", "X = -zexecstack\n", ["execstack"]),
    ("Makefile", "X = -Xlinker -z -Xlinker execstack\n", ["execstack"]),
    ("Makefile", "X = -Wl,-z -Wl,execstack\n", ["execstack"]),
    ("Makefile", "X = -Wl,-z,noexecstack -z noexecstack -Wl,-z,relro,-z,now\n", []),
    ("Makefile", "X = -Wl,-z,norelro\n", ["norelro"]),
    ("Makefile", "X = -fcf-protection=none\n", ["cf-protection-none"]),
    ("Makefile", "X = -fcf-protection=full -fcf-protection\n", []),
    ("Makefile", "X = -mno-shstk\n", ["no-shstk"]),
    ("Makefile", "X = -fstack-protector-strong -fstack-protector-all -O2\n", []),
    ("Makefile", "X = -fno-stack-protector -fno-stack-protector\n", ["no-stack-protector"] * 2),
    ("Makefile", "X = -DCMAKE_POSITION_INDEPENDENT_CODE=OFF\n", ["cmake-position-independent-code-off"]),
    ("Makefile", "X = -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=OFF\n", ["cmake-position-independent-code-off"]),
    ("Makefile", "export CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS=false\n", ["rust-overflow-checks-env"]),
    ("Makefile", "RUSTFLAGS = -C overflow-checks=off\n", ["rust-overflow-checks-flag"]),
    (
        "Makefile",
        "RUSTFLAGS = -Coverflow-checks=no -C relocation-model=static\n",
        ["rust-overflow-checks-flag", "rust-relocation-model-static"],
    ),
    ("Makefile", "RUSTFLAGS = -C overflow-checks=on -C relocation-model=pic\n", []),
]
SHELL = [
    ("build.sh", "go build -ldflags '-extldflags \"-static -no-pie\"' ./...\n", ["no-pie"]),
    ("build.sh", "go build -ldflags=-extldflags=-no-pie ./...\n", ["no-pie"]),
    ("ci/build.bash", 'export CGO_CFLAGS="-O2 -fno-stack-protector"\n', ["no-stack-protector"]),
    ("build.sh", "export CGO_LDFLAGS='-Wl,-z,execstack'\n", ["execstack"]),
    ("build.sh", "go build ./... # -no-pie\n# -fno-stack-protector\n", []),
    ("build.sh", 'echo "# x" -no-pie\n', ["no-pie"]),
    ("build.sh", "echo '#' -no-pie\n", ["no-pie"]),
    ("build.sh", "echo \\# -no-pie\n", ["no-pie"]),
    ("build.sh", "true;# -no-pie\n", []),
    ("build.sh", "echo it's # fine\necho -no-pie\n", ["no-pie"]),
    ("build.sh", 'X="\n # -no-pie\n"\n', ["no-pie"]),
    ("build.sh", "cc a.c \\\n  -fno-stack-protector\n", ["no-stack-protector"]),
    ("build.sh", "cc a.c \\\\\n-no-pie\n", ["no-pie"]),
    ("Dockerfile", "RUN gcc -z \\\n # why\n  execstack x.c\n", ["execstack"]),
    ("Dockerfile", "# RUN gcc -no-pie\nFROM scratch\n", []),
    ("Dockerfile", "ENV CGO_CFLAGS=-fno-stack-protector\n", ["no-stack-protector"]),
    ("app.Dockerfile", "RUN cc -no-pie\n", ["no-pie"]),
    ("Containerfile", "RUN cc -no-pie\n", ["no-pie"]),
    (".goreleaser.yaml", "builds:\n  - ldflags:\n      - -s -w -extldflags=-no-pie\n", ["no-pie"]),
    (".goreleaser.yml", "builds:\n  - env:\n      - CGO_CFLAGS=-fno-stack-protector # why\n", ["no-stack-protector"]),
    (".goreleaser.yml", "# -no-pie\nbuilds: []\n", []),
    ("configure.ac", "AC_SUBST([X], [-fno-stack-protector])\ndnl x\n# -no-pie\n", ["no-stack-protector"]),
    ("meson.build", "add_project_arguments('-fno-stack-protector', language: 'c')\n", ["no-stack-protector"]),
    ("meson.build", "# -no-pie\nx = 'a \\' # -no-pie'\n", ["no-pie"]),
    ("meson.build", "x = '''\n# -no-pie\n'''\n", ["no-pie"]),
    ("meson.build", "x = '''never closed -no-pie\n", ["no-pie"]),
    ("meson.build", "add_project_link_arguments(\n  '-z',\n  'execstack',\n)\n", ["execstack"]),
    ("meson.build", "add_project_link_arguments('-Wl,-z,execstack')\n", ["execstack"]),
    ("meson.build", "add_project_link_arguments('-z', 'norelro', language: 'c')\n", ["norelro"]),
    ("meson.build", "executable('x', 'x.c', pie: false)\n", ["meson-pie-off"]),
    ("meson.build", "project('x', 'c', default_options: ['b_pie=false'])\n", ["meson-pie-off"]),
    ("meson.build", "executable('x', 'x.c', pie: true, install: false)\n", []),
    ("CMakeLists.txt", 'target_link_options(t PRIVATE "-z" "execstack")\n', ["execstack"]),
    ("CMakeLists.txt", "add_compile_options(-DX=\\# -fno-stack-protector)\n", ["no-stack-protector"]),
    ("CMakeLists.txt", "add_compile_options(-DX=\\# -D_FORTIFY_SOURCE=0)\n", ["fortify-source-zero"]),
    (
        "build.sh",
        'gcc -z \'execstack\' x.c\ngcc -z "norelro" x.c\ngcc -Wl,-z,"execstack" x.c\n',
        ["execstack"] * 2 + ["norelro"],
    ),
    ("configure.ac", "dnl -fno-stack-protector\nAC_PROG_CC # -no-pie\n", []),
    ("configure.ac", "AC_PROG_CC dnl -no-pie\nCFLAGS=-no-pie\n", ["no-pie"]),
]
CARGO = [
    ("Cargo.toml", "[profile.release]\noverflow-checks = false\n", ["rust-overflow-checks-release"]),
    ("Cargo.toml", "[profile.release]\noverflow-checks = true\n", []),
    ("Cargo.toml", '[profile.dev]\noverflow-checks = false\n[profile.release]\npanic = "abort"\n', []),
    ("Cargo.toml", '[profile.release.package."*"]\noverflow-checks = false\n', ["rust-overflow-checks-release"]),
    ("Cargo.toml", "[profile.release]\npackage.foo.overflow-checks = false\n", ["rust-overflow-checks-release"]),
    ("Cargo.toml", "[ profile . release ]\noverflow-checks=false # why\n", ["rust-overflow-checks-release"]),
    ("Cargo.toml", "[profile.release]\nopt-level = 3\n[[bin]]\noverflow-checks = false\n", []),
    ("Cargo.toml", "profile.release.overflow-checks = false\n", ["rust-overflow-checks-release-dotted"]),
    (
        "Cargo.toml",
        "[profile]\nrelease = { opt-level = 3, overflow-checks = false }\n",
        ["rust-overflow-checks-release-inline"],
    ),
    ("Cargo.toml", "[profile]\ndev = { overflow-checks = false }\n", []),
    ("Cargo.toml", "[profile.release]\nlto = true\n", []),
    (
        ".cargo/config.toml",
        '[build]\nrustflags = ["-C", "relocation-model=static"]\n',
        ["rust-relocation-model-static"],
    ),
    (
        ".cargo/config",
        'rustflags = [\n  "-C",\n  "relocation-model=static", # why\n]\n',
        ["rust-relocation-model-static"],
    ),
    (".cargo/config.toml", 'rustflags = ["-Crelocation-model=static"]\n', ["rust-relocation-model-static"]),
    (".cargo/config.toml", 'rustflags = ["-C", "link-arg=-no-pie"]\n', ["no-pie"]),
    (
        ".cargo/config.toml",
        'rustflags = ["-C", "link-arg=-z", "-C", "link-arg=execstack"]\n',
        ["rust-link-arg-z-weaken"],
    ),
    (".cargo/config.toml", "rustflags = '-C link-arg=-z -C link-arg=norelro'\n", ["rust-link-arg-z-weaken"]),
    (".cargo/config.toml", 'rustflags = ["-C", "link-arg=-Wl,-z,execstack"]\n', ["execstack"]),
    (".cargo/config.toml", 'rustflags = ["-C", "relocation-model=pic"]\n', []),
    (".cargo/config.toml", '[env]\nCARGO_PROFILE_RELEASE_OVERFLOW_CHECKS = "false"\n', ["rust-overflow-checks-env"]),
    ("Cargo.toml", 'x = """\n# -no-pie\n"""\ny = \'a # b\' # -no-pie\n', ["no-pie"]),
    ("Cargo.toml", "x = 'C:\\\\' # -no-pie\nflags = ['-no-pie']\n", ["no-pie"]),
    ("Cargo.toml", 'x = """never closed # -no-pie\n', ["no-pie"]),
    ("Cargo.toml", '[profile.release]\n"overflow-checks" = false\n', ["rust-overflow-checks-release"]),
    ("Cargo.toml", "[profile]\nrelease.overflow-checks = false\n", ["rust-overflow-checks-release-inline"]),
    (".cargo/config.toml", 'rustflags = ["--codegen", "relocation-model=static"]\n', ["rust-relocation-model-static"]),
    (".cargo/config.toml", "rustflags = ['--codegen=relocation-model=static']\n", ["rust-relocation-model-static"]),
]
RUST = [
    ("build.rs", 'fn main() {\n    println!("cargo:rustc-link-arg=-no-pie");\n}\n', ["no-pie"]),
    ("build.rs", 'fn main() { cc::Build::new().flag("-fno-stack-protector"); }\n', ["no-stack-protector"]),
    ("build.rs", "// -no-pie\nfn main() {} // -fno-pie\n", []),
    ("build.rs", "/* -no-pie /* nested -no-pie */ still -no-pie */ fn main() {}\n", []),
    ("build.rs", "/* never closed -no-pie\n", []),
    ("build.rs", '/* a */ let a = "-no-pie";\n', ["no-pie"]),
    ("build.rs", 'let a = r#"-no-pie"#;\n', ["no-pie"]),
    ("build.rs", 'let a = r"//"; let b = "-no-pie";\n', ["no-pie"]),
    ("build.rs", 'let a = r#"never closed -no-pie\n', ["no-pie"]),
    ("build.rs", 'let q = \'"\'; let b = "-no-pie";\n', ["no-pie"]),
    ("build.rs", "let q = '\\''; let b = \"-no-pie\";\n", ["no-pie"]),
    ("build.rs", "fn f<'a>(x: &'a str) { let b = \"-no-pie\"; }\n", ["no-pie"]),
    ("build.rs", 'let a = "a\\"b -no-pie";\n', ["no-pie"]),
    ("build.rs", 'let a = "never closed -no-pie\n', ["no-pie"]),
    (
        "build.rs",
        'Command::new("cc").args([\n  "-C",\n  "relocation-model=static",\n]);\n',
        ["rust-relocation-model-static"],
    ),
    ("build.rs", 'Command::new("ld").arg("-z").arg("execstack");\n', []),
    ("build.rs", 'let a = 1 // "-no-pie"\n', []),
    ("build.rs", 'let a = br"\\"; let b = "//"; let c = "-fno-stack-protector";\n', ["no-stack-protector"]),
]
KERNEL = [
    ("board_defconfig", "# CONFIG_STACKPROTECTOR is not set\n", ["kernel-stackprotector-off"]),
    ("defconfig", "CONFIG_STACKPROTECTOR=n\n", ["kernel-stackprotector-off"]),
    ("a.config", "CONFIG_STACKPROTECTOR=n  # why\n", ["kernel-stackprotector-off"]),
    (".config", "  # CONFIG_STRICT_KERNEL_RWX is not set\n", ["kernel-strict-rwx-off"]),
    ("x.config", "CONFIG_RANDOMIZE_BASE=n\n# CONFIG_RANDOMIZE_BASE is not set\n", ["kernel-kaslr-off"] * 2),
    ("x.config", "CONFIG_HARDENED_USERCOPY=n\n", ["kernel-hardened-usercopy-off"]),
    ("x.config", "# CONFIG_FORTIFY_SOURCE is not set\n", ["kernel-fortify-source-off"]),
    ("x.config", "CONFIG_DEVMEM=y\n", ["kernel-devmem"]),
    ("x.config", "CONFIG_STRICT_DEVMEM=n\n# CONFIG_STRICT_DEVMEM is not set\n", ["kernel-strict-devmem-off"] * 2),
    ("x.config", "CONFIG_STACKPROTECTOR=N\n# config_stackprotector is not set\nconfig_stackprotector=n\n", []),
    ("x.config", "CONFIG_STACKPROTECTOR=y\nCONFIG_STACKPROTECTOR_STRONG=n\n# CONFIG_FOO is not set\n", []),
    ("x.config", "# note: CONFIG_STACKPROTECTOR=n is unsafe\n# was CONFIG_RANDOMIZE_BASE=n\n", []),
    ("x.config", "CONFIG_DEVMEM=n\nCONFIG_STRICT_DEVMEM=y\n", []),
    ("x.config", "-fno-stack-protector\n", []),
]
UNSCANNED = [
    ("src/main.c", "int x; /* -fno-stack-protector */ CFLAGS = -no-pie\n", []),
    ("docs/flags.md", "CFLAGS = -fno-stack-protector\n", []),
    ("tool.py", "FLAGS = ['-fno-stack-protector']\n", []),
    ("flags.json", '{"flags": "-no-pie"}\n', []),
    ("CMakePresets.json", '{"CMAKE_C_FLAGS": "-fno-stack-protector"}\n', []),
]
