#!/usr/bin/env python3
"""Generate docs/<id>/adoption.md: the output of adopting each policy into a fresh repo.

A contributor's claim that "the policy works" is worth nothing attached to a PR as pasted
console output -- pasted output can be edited, and goes stale the moment anything changes.
So the claim is committed as a file this tool generates, and CI regenerates it with
`--check`: a transcript that cannot be re-derived from an empty repository fails the build,
exactly the contract the coverage matrix and policy docs already follow.

Each transcript is a real adoption, not a description of one: an empty git repository,
`chock init`, the one policy copied in, then recompile, install-hooks, validate and
eval. Any command exiting non-zero aborts generation -- a policy that cannot be adopted
cleanly does not get a transcript that pretends it can.

Output is normalized so the same adoption produces the same bytes on any machine: the
scratch path becomes `…`, backslashes become slashes, and environment-specific lines
(the Windows skills-bridge symlink warning) are dropped. What remains is what the tools
printed. Transcripts also pin framework output: when the framework changes what a command
prints, the transcripts of every *touched* policy must be regenerated -- untouched policies
drift silently until their next edit, the same trade the reviewer-evidence step makes.

Usage:
  python tools/gen_adoption_transcript.py                  # write all transcripts
  python tools/gen_adoption_transcript.py --policy <id>    # write one
  python tools/gen_adoption_transcript.py --check          # diff all against committed
  python tools/gen_adoption_transcript.py --check --base origin/main
                                                           # diff only policies changed vs base;
                                                           # a changed policy with no committed
                                                           # transcript fails
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

from trees import TREES, policy_dirs

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"

#: Commands an adopter runs, in order. `cp` is rendered informatively; the rest execute.
STEPS = ("recompile --repo .", "install-hooks .", "validate .", "eval --repo .")

#: Lines that describe the machine, not the adoption.
ENV_NOISE = re.compile(r"skills-bridge|symlink", re.IGNORECASE)

MARK = "<!-- generated by tools/gen_adoption_transcript.py; do not edit -->"


def _run(cmd: list[str], cwd: Path) -> tuple[int, str]:
    proc = subprocess.run(
        cmd, cwd=cwd, capture_output=True, text=True, encoding="utf-8", errors="replace",
        env={**__import__("os").environ, "PYTHONUTF8": "1", "PYTHONIOENCODING": "utf-8"},
    )
    return proc.returncode, (proc.stdout or "") + (proc.stderr or "")


def _normalize(text: str, scratch: Path) -> str:
    for variant in (str(scratch), str(scratch).replace("\\", "/")):
        text = text.replace(variant, "…")
    text = text.replace("\\", "/")
    lines = [ln.rstrip() for ln in text.splitlines() if not ENV_NOISE.search(ln)]
    return "\n".join(lines).strip("\n")


def _index_entry(adopter: Path, policy_id: str) -> str:
    index = adopter / ".agents" / "policies" / "INDEX.md"
    if not index.exists():
        return ""
    lines = index.read_text(encoding="utf-8").splitlines()
    out: list[str] = []
    for line in lines:
        if out:
            if line.startswith("- **") or line.startswith("#"):
                break
            out.append(line.rstrip())
        elif line.startswith(f"- **{policy_id}**"):
            out.append(line.rstrip())
    return "\n".join(out).strip("\n")


def build_transcript(policy_dir: Path) -> str:
    policy_id = policy_dir.name
    tree = policy_dir.parent.name
    chock = shutil.which("chock")
    if not chock:
        raise SystemExit("chock is not on PATH; install the framework first.")

    with tempfile.TemporaryDirectory(prefix="adopt-") as tmp:
        adopter = Path(tmp)
        for cmd in (["git", "init", "--quiet", "."],
                    ["git", "config", "user.email", "adopter@chock.invalid"],
                    ["git", "config", "user.name", "adopter"]):
            code, out = _run(cmd, adopter)
            if code != 0:
                raise SystemExit(f"{policy_id}: `{' '.join(cmd)}` failed:\n{out}")

        sections: list[tuple[str, str]] = []
        code, out = _run([chock, "init", "."], adopter)
        if code != 0:
            raise SystemExit(f"{policy_id}: `chock init .` failed:\n{out}")
        sections.append(("chock init .", _normalize(out, adopter)))

        shutil.copytree(policy_dir, adopter / ".agents" / "policies" / policy_id)
        sections.append((f"cp -r {tree}/{policy_id} .agents/policies/{policy_id}", "(no output)"))

        for step in STEPS:
            argv = [chock, *step.split()]
            code, out = _run(argv, adopter)
            if code != 0:
                raise SystemExit(f"{policy_id}: `chock {step}` exited {code}:\n{out}")
            sections.append((f"chock {step}", _normalize(out, adopter)))

        compiled = adopter / ".chock" / "compiled" / policy_id
        surfaces = "\n".join(
            sorted(p.relative_to(adopter).as_posix() for p in compiled.rglob("*") if p.is_file())
        ) if compiled.is_dir() else "(nothing compiled)"
        index_entry = _index_entry(adopter, policy_id)

    parts = [
        f"# {policy_id} — adoption transcript",
        "",
        MARK,
        f"<!-- regenerate: python tools/gen_adoption_transcript.py --policy {policy_id} -->",
        "",
        "An empty repository, `chock init`, this one policy copied in, and every",
        "command an adopter runs. CI re-derives this file with `--check`; a transcript that",
        "cannot be reproduced fails the build. Paths are normalized to `…`, backslashes to",
        "slashes, and environment-specific lines removed.",
        "",
    ]
    for command, output in sections:
        parts += [f"## `$ {command}`", "", "```text", output or "(no output)", "```", ""]
    parts += ["## Compiled surfaces", "", "```text", surfaces, "```", ""]
    if index_entry:
        parts += ["## INDEX.md entry", "", "```text", index_entry, "```", ""]
    return "\n".join(parts)


def changed_policy_ids(base: str) -> set[str]:
    proc = subprocess.run(
        ["git", "diff", "--name-only", f"{base}...HEAD"],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8",
    )
    if proc.returncode != 0:
        raise SystemExit(f"git diff against {base} failed:\n{proc.stderr}")
    changed: set[str] = set()
    for line in proc.stdout.splitlines():
        parts = Path(line.strip()).parts
        if len(parts) >= 2 and parts[0] in TREES:
            changed.add(parts[1])
        # A touched transcript re-derives too: an adoption.md edited by hand instead of
        # regenerated is exactly the fabrication this check exists to refuse.
        elif len(parts) == 3 and parts[0] == "docs" and parts[2] == "adoption.md":
            changed.add(parts[1])
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate or check adoption transcripts.")
    parser.add_argument("--check", action="store_true", help="diff against committed transcripts")
    parser.add_argument("--policy", help="limit to one policy id")
    parser.add_argument("--base", help="limit to policies changed vs this ref (requires --check)")
    args = parser.parse_args(argv)

    targets = [d for d in policy_dirs() if not args.policy or d.name == args.policy]
    if args.policy and not targets:
        print(f"No policy named {args.policy!r} in {'/'.join(TREES)}.", file=sys.stderr)
        return 2
    if args.base:
        changed = changed_policy_ids(args.base)
        targets = [d for d in targets if d.name in changed]
        if not targets:
            print(f"No policies changed vs {args.base}; nothing to verify.")
            return 0

    problems: list[str] = []
    for policy_dir in targets:
        path = DOCS / policy_dir.name / "adoption.md"
        fresh = build_transcript(policy_dir)
        if args.check:
            if not path.exists():
                problems.append(
                    f"{policy_dir.name}: no committed transcript. Run "
                    f"`python tools/gen_adoption_transcript.py --policy {policy_dir.name}` and commit docs/{policy_dir.name}/adoption.md"
                )
            else:
                committed = path.read_text(encoding="utf-8").replace("\r\n", "\n")
                if committed != fresh:
                    import difflib

                    diff = "".join(
                        difflib.unified_diff(
                            committed.splitlines(keepends=True), fresh.splitlines(keepends=True),
                            fromfile=f"docs/{policy_dir.name}/adoption.md (committed)",
                            tofile=f"docs/{policy_dir.name}/adoption.md (fresh adoption)",
                        )
                    )
                    problems.append(
                        f"{policy_dir.name}: committed transcript does not match a fresh adoption. "
                        f"Regenerate with `--policy {policy_dir.name}`.\n{diff}"
                    )
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(fresh, encoding="utf-8", newline="\n")

    if args.check:
        if problems:
            print(f"Adoption transcript drift ({len(problems)} problem(s)):", file=sys.stderr)
            for p in problems:
                print(f"  - {p}", file=sys.stderr)
            return 1
        print(f"Adoption transcripts match: {len(targets)} polic(y/ies) re-adopted from empty repos.")
        return 0
    print(f"Wrote {len(targets)} adoption transcript(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
